import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";

globalThis.HTMLElement = class {};
globalThis.customElements = {definitions:new Map(),get(name){return this.definitions.get(name);},define(name,value){this.definitions.set(name,value);}};
globalThis.window = {};
globalThis.CustomEvent = class {constructor(type,options){this.type=type;Object.assign(this,options);}};
const fakeElement=localName=>({localName,children:[],attributes:{},listeners:{},append(...children){this.children.push(...children);},setAttribute(name,value){this.attributes[name]=value;},addEventListener(name,listener){this.listeners[name]=listener;}});
globalThis.document = {createElement:fakeElement};
globalThis.fetch = async url => {
  const language=String(url).match(/\/([a-z]{2,3})\.json$/)?.[1]||"en";
  const catalog=JSON.parse(readFileSync(new URL(`../../custom_components/home_tasker/translations/${language}.json`,import.meta.url),"utf8"));
  return {ok:true,json:async()=>catalog};
};

const {ready,setLanguage}=await import("../../custom_components/home_tasker/frontend/localize.js");
await ready;
await setLanguage("en");
const {DEFAULT_CARD_CONFIG,HomeTaskerCardEditor,UNASSIGNED,canEditCard,dashboardCardBodyHtml,dashboardTaskRowHtml,dueStatus,filterDashboardTasks,normalizeCardConfig,sortDashboardTasks}=await import("../../custom_components/home_tasker/frontend/dashboard-card.js");
const {HomeTaskerBase,HomeTaskerPanel}=await import("../../custom_components/home_tasker/frontend/main.js");
const {EDITOR_FILE_GRID}=await import("../../custom_components/home_tasker/frontend/task-editor.js");
const {TASK_DIALOG_TAG,showTaskDialog}=await import("../../custom_components/home_tasker/frontend/native-task-dialog.js");
const {ATTACHMENT_DIALOG_TAG,attachmentPreviewHtml,showAttachmentDialog}=await import("../../custom_components/home_tasker/frontend/native-attachment-dialog.js");
const {CONFIRM_DIALOG_TAG,FORM_DIALOG_TAG,formDialogFooterHtml,showFormDialog,showNativeConfirmation}=await import("../../custom_components/home_tasker/frontend/native-form-dialog.js");
const {createActionMenu}=await import("../../custom_components/home_tasker/frontend/action-menu.js");
const {taskDetailBoxHtml,taskFilesBoxHtml,taskHistoryBoxHtml}=await import("../../custom_components/home_tasker/frontend/task-detail-boxes.js");

const tasks=[
  {id:"old",name:"Mopping",due_date:"2026-07-20",group_id:"house",assignee_user_id:"alice"},
  {id:"today",name:"Dishes",due_date:"2026-07-21",group_id:"kitchen",assignee_user_id:null},
  {id:"soon",name:"Bad",due_date:"2026-07-24",group_id:"house",assignee_user_id:"bob"},
  {id:"later",name:"Windows",due_date:"2026-08-01",group_id:"house",assignee_user_id:null},
];

test("default config shows overdue and today",()=>assert.deepEqual(filterDashboardTasks(tasks,DEFAULT_CARD_CONFIG,"2026-07-21").map(task=>task.id),["old","today"]));
test("due day window includes its future boundary",()=>assert.deepEqual(filterDashboardTasks(tasks,{due_days:3},"2026-07-21").map(task=>task.id),["old","today","soon"]));
test("null due day window includes every due date",()=>assert.equal(filterDashboardTasks(tasks,{due_days:null},"2026-07-21").length,4));
test("group and assignee filters use OR within and AND between",()=>assert.deepEqual(filterDashboardTasks(tasks,{due_days:null,group_ids:["house","garage"],assignee_user_ids:["alice",UNASSIGNED]},"2026-07-21").map(task=>task.id),["old","later"]));

test("sorting always puts the oldest tasks first with a name tiebreaker without mutation",()=>{const input=[{id:"b",name:"Zulu",due_date:"2026-07-21"},{id:"a",name:"Alpha",due_date:"2026-07-21"},{id:"c",name:"Later",due_date:"2026-07-22"}],original=[...input];assert.deepEqual(sortDashboardTasks(input).map(task=>task.id),["a","b","c"]);assert.deepEqual(input,original);});
test("normalization preserves null, sanitizes invalid values, and removes unsupported options",()=>{assert.equal(normalizeCardConfig({due_days:null}).due_days,null);assert.equal(normalizeCardConfig({due_days:-2,mode:"other"}).due_days,0);assert.equal(normalizeCardConfig({mode:"other"}).mode,"view");assert.equal(normalizeCardConfig({sort_direction:"desc",hide_card_background:true}).sort_direction,undefined);assert.equal(normalizeCardConfig({hide_card_background:true}).hide_card_background,undefined);});

test("due status separates overdue, today, and future dates",()=>{assert.equal(dueStatus("2026-07-20","2026-07-21"),"overdue");assert.equal(dueStatus("2026-07-21","2026-07-21"),"today");assert.equal(dueStatus("2026-07-22","2026-07-21"),"future");});
test("dashboard tasks use neutral Home Assistant tile surfaces",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/background:var\(--ha-card-background,var\(--card-background-color\)\)/);assert.match(source,/border:1px solid var\(--ha-card-border-color,var\(--divider-color\)\)/);assert.doesNotMatch(source,/background:color-mix\(in srgb,var\(--task-color/);assert.match(source,/\.due-date\.overdue\{color:var\(--error-color/);});
test("view rows show the shared due, assignee, and NFC pill line without actions",()=>{const html=dashboardTaskRowHtml(tasks[0],false,"yesterday","overdue","Alice","Laundry tag");assert.doesNotMatch(html,/dots-vertical|row-action-toggle|house/);assert.match(html,/Mopping/);assert.match(html,/pill due-date overdue/);assert.match(html,/mdi:account[\s\S]*Alice/);assert.match(html,/mdi:nfc[\s\S]*Laundry tag/);});
test("dashboard uses shared pill styles while due pills retain status colors",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/this\.themeStyles\(\)\+this\.pillStyles\(\)/);assert.doesNotMatch(source,/taskSurfaceStyles|\.pills \.pill:not\(\.due-date\)\{color:/);assert.match(source,/\.due-date\.today\{color:var\(--warning-color/);assert.match(source,/\.due-date\.overdue\{color:var\(--error-color/);assert.match(source,/\.due-date\.future\{color:var\(--success-color/);});
test("dashboard retains its shared pill stylesheet while the panel delegates rows to HA",()=>{const dashboard=readFileSync(new URL("../../custom_components/home_tasker/frontend/dashboard-card.js",import.meta.url),"utf8"),list=readFileSync(new URL("../../custom_components/home_tasker/frontend/task-list.js",import.meta.url),"utf8");assert.match(dashboard,/this\.themeStyles\(\)\+this\.pillStyles\(\)/);assert.match(list,/hass-tabs-subpage-data-table/);assert.doesNotMatch(list,/this\.pillStyles\(\)|taskRow\(/);assert.doesNotMatch(dashboard,/pillIconCss\(\)/);});
test("edit rows reserve a native action-menu slot",()=>{const html=dashboardTaskRowHtml(tasks[0],true,"yesterday","overdue");assert.match(html,/class="row-action-slot"/);assert.doesNotMatch(html,/row-action-menu|style=/);});
test("shared action menu uses native HA dropdown controls and dispatches actions",()=>{let edited=0,removed=0,stopped=0;const menu=createActionMenu({label:"Task actions",edit:()=>edited++,remove:()=>removed++});assert.equal(menu.localName,"ha-dropdown");assert.deepEqual(menu.children.map(child=>child.localName),["ha-icon-button","ha-dropdown-item","ha-dropdown-item"]);assert.equal(menu.children[0].attributes["aria-label"],"Task actions");assert.equal(menu.children[2].attributes.variant,"danger");menu.listeners.pointerdown({stopPropagation:()=>stopped++});menu.listeners.click({stopPropagation:()=>stopped++});menu.listeners["wa-select"]({stopPropagation:()=>stopped++,detail:{item:{value:"edit"}}});menu.listeners["wa-select"]({stopPropagation:()=>stopped++,detail:{item:{value:"delete"}}});assert.equal(edited,1);assert.equal(removed,1);assert.equal(stopped,4);});
test("edit mode is controlled only by card configuration",()=>{assert.equal(canEditCard({mode:"edit"}),true);assert.equal(canEditCard({mode:"view"}),false);});

test("editor update emits a dashboard-local config change",()=>{const editor=Object.create(HomeTaskerCardEditor.prototype);editor.config={...DEFAULT_CARD_CONFIG};editor.render=()=>{};let event;editor.dispatchEvent=value=>{event=value;};editor.update({mode:"edit",group_ids:["house"]});assert.equal(event.type,"config-changed");assert.equal(event.detail.config.mode,"edit");assert.deepEqual(event.detail.config.group_ids,["house"]);});
test("repeated hass updates do not rerender and steal editor focus",()=>{const editor=Object.create(HomeTaskerCardEditor.prototype);editor.loaded=true;let renders=0;editor.render=()=>{renders++;};Object.getOwnPropertyDescriptor(HomeTaskerCardEditor.prototype,"hass").set.call(editor,{user:{}});assert.equal(renders,0);});
test("shared controller reloads from Home Tasker events",async()=>{const controller=Object.create(HomeTaskerBase.prototype);controller.eventUnsubscribe=null;controller.eventSubscriptionToken=0;let listener,eventType,loads=0;controller._hass={connection:{subscribeEvents:async(callback,type)=>{listener=callback;eventType=type;return()=>{};}}};controller.load=async()=>{loads++;};await controller.subscribeEvents();assert.equal(eventType,"home_tasker_event");await listener({data:{action:"updated",resource_type:"task"}});assert.equal(loads,1);});
test("shared controller removes stale event subscriptions",async()=>{const controller=Object.create(HomeTaskerBase.prototype);controller.eventUnsubscribe=null;controller.eventSubscriptionToken=0;let removed=0;controller._hass={connection:{subscribeEvents:async()=>()=>{removed++;}}};await controller.subscribeEvents();controller.unsubscribeEvents();assert.equal(removed,1);assert.equal(controller.eventUnsubscribe,null);});
test("ordinary hass updates no longer reload task data",async()=>{const controller=Object.create(HomeTaskerBase.prototype),descriptor=Object.getOwnPropertyDescriptor(HomeTaskerBase.prototype,"hass"),settle=()=>new Promise(resolve=>setImmediate(resolve));controller.loaded=true;controller.eventUnsubscribe=()=>{};controller.eventSubscriptionToken=0;let loads=0,renders=0;controller.load=async()=>{loads++;};controller.render=()=>{renders++;};const connection={subscribeEvents:async()=>()=>{}};descriptor.set.call(controller,{connection,locale:{language:"en"},states:{"binary_sensor.task":{state:"on"}}});await settle();descriptor.set.call(controller,{connection,locale:{language:"en"},states:{"binary_sensor.task":{state:"off"}}});await settle();assert.equal(loads,0);assert.equal(renders,0);});
test("concurrent loads are coalesced into one pending reload",async()=>{const controller=Object.create(HomeTaskerBase.prototype);controller._hass={};controller.loading=true;controller.reloadPending=false;await controller.load();await controller.load();assert.equal(controller.reloadPending,true);});
test("panel uses an unregistered shared base instead of becoming the card base",async()=>{const {HomeTaskerCard}=await import("../../custom_components/home_tasker/frontend/dashboard-card.js");assert.equal(Object.getPrototypeOf(HomeTaskerPanel),HomeTaskerBase);assert.equal(Object.getPrototypeOf(HomeTaskerCard),HomeTaskerBase);assert.notEqual(Object.getPrototypeOf(HomeTaskerCard),HomeTaskerPanel);});
test("task viewer opens through Home Assistant's native show-dialog contract",()=>{let event;const controller={dispatchEvent:value=>{event=value;}};showTaskDialog(controller,tasks[0]);assert.equal(event.type,"show-dialog");assert.equal(event.bubbles,true);assert.equal(event.composed,true);assert.equal(event.detail.dialogTag,TASK_DIALOG_TAG);assert.equal(event.detail.dialogParams.task,tasks[0]);});
test("task viewer delegates descriptions to Home Assistant markdown",()=>{const viewer=readFileSync(new URL("../../custom_components/home_tasker/frontend/native-task-dialog.js",import.meta.url),"utf8"),shared=readFileSync(new URL("../../custom_components/home_tasker/frontend/shared.js",import.meta.url),"utf8");assert.match(viewer,/<ha-markdown class="description ht-content" breaks>/);assert.match(viewer,/markdown\.content=task\.description/);assert.doesNotMatch(viewer,/markdown\(task\.description\)/);assert.doesNotMatch(shared,/markdownInline|export const markdown/);});
test("task viewer uses outlined native expansion panels and a reliable notes field",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/native-task-dialog.js",import.meta.url),"utf8"),boxes=readFileSync(new URL("../../custom_components/home_tasker/frontend/task-detail-boxes.js",import.meta.url),"utf8");assert.match(source,/controller\.typographyStyles\(\)/);assert.match(source,/taskDetailBoxHtml\(t\("task\.description"\),description,\{expanded:true\}\)/);assert.match(source,/taskDetailBoxHtml\(t\("task\.planning"\),[^;]+\{expanded:true\}\)/);assert.match(source,/taskDetailBoxHtml\(t\("task\.completion_notes"\),notes/);assert.match(source,/class="pill ht-content-small"/);assert.match(source,/<textarea class="completion-notes"/);assert.match(source,/border:1px solid var\(--divider-color\)/);assert.match(boxes,/<ha-expansion-panel outlined/);assert.doesNotMatch(source,/taskDetailBoxHtml\(t\("task\.name"\)|applyTypography|<ha-textarea|<details|<summary/);});
test("task detail box helper delegates header typography and outlines to Home Assistant",()=>{assert.match(taskDetailBoxHtml("Name","Task",{expanded:true}),/^<ha-expansion-panel outlined expanded>/);assert.match(taskDetailBoxHtml("Files","None",{className:"files-box"}),/^<ha-expansion-panel outlined class="files-box">/);assert.doesNotMatch(taskDetailBoxHtml("Name","Task"),/slot="header" class=/);});
test("completion confirmation is dispatched by the panel controller",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/native-task-dialog.js",import.meta.url),"utf8");assert.match(source,/showNativeConfirmation\(this\.controller,/);assert.doesNotMatch(source,/showNativeConfirmation\(this,/);});
test("completion tolerates an untouched native notes field",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/native-task-dialog.js",import.meta.url),"utf8");assert.match(source,/\.value\|\|""\)\.trim\(\)\|\|null/);});
test("task viewer places the due date above the recurrence description",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/native-task-dialog.js",import.meta.url),"utf8");assert.match(source,/scheduleText\(task\)\.split\("\\n"\)\.reverse\(\)\.join\("\\n"\)/);});
test("task viewer appends the assigned tag name as an NFC pill",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/native-task-dialog.js",import.meta.url),"utf8");assert.match(source,/this\.render\(\);[\s\S]*?this\.addTagPill\(\);this\.loadHistory\(\)/);assert.doesNotMatch(source,/applyPillIconStyles|style\.textContent/);assert.match(source,/className="pill ht-content-small"/);assert.match(source,/mdi:nfc/);assert.match(source,/controller\.tagName\(this\.task\)/);});
test("task editor loads Home Assistant tags into a select",()=>{const main=readFileSync(new URL("../../custom_components/home_tasker/frontend/main.js",import.meta.url),"utf8"),editor=readFileSync(new URL("../../custom_components/home_tasker/frontend/task-editor.js",import.meta.url),"utf8");assert.match(main,/this\.ws\(\{type:"tag\/list"\}\)/);assert.match(main,/this\.tags=Array\.isArray\(tags\)\?tags:\[\]/);assert.match(editor,/tagOptions=\[\.\.\.this\.tags\]/);assert.match(editor,/\["nfc_tag_id",tr\("task\.nfc_tag_id"\)[\s\S]*?"select"/);assert.match(editor,/tr\("task\.no_nfc_tag"\)/);});
test("editor fields assign typography classes by role",()=>{const controller=Object.create(HomeTaskerBase.prototype);assert.match(controller.field(["name","Name","",true]),/class="ht-label-medium"[\s\S]*class="ht-content"/);assert.match(controller.field(["recurrence_mode","Calculate due date","fixed",true,"select",[["fixed","Calendar"]]]),/class="ht-label-normal"[\s\S]*class="ht-content"/);assert.match(controller.field(["manufacturer","Manufacturer",""]),/class="ht-label-medium"[\s\S]*class="ht-content"/);});
test("editor sections are created directly as outlined native expansion panels",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/task-editor.js",import.meta.url),"utf8"),dialogs=readFileSync(new URL("../../custom_components/home_tasker/frontend/dialogs.js",import.meta.url),"utf8");assert.match(source,/createElement\("ha-expansion-panel"\)/);assert.match(source,/panel\.outlined=true/);assert.match(source,/panel\.expanded=expanded/);assert.match(source,/arrangeBasics\(modal\)/);assert.match(source,/\["name",tr\("task\.name"\),"name-box"\]/);assert.match(source,/\["description",tr\("task\.description"\),"description-box"\]/);assert.match(source,/expansionPanel\(className,title,true\)/);assert.match(source,/header\.slot="header"/);assert.doesNotMatch(dialogs,/prepareDetails|details-toggle|MutationObserver/);});
test("editors and confirmations use registered native dialog contracts",()=>{const events=[],controller={dispatchEvent:event=>events.push(event)};showFormDialog(controller,{title:"Editor",fields:[]});showNativeConfirmation(controller,{title:"Delete",message:"Sure?",confirmLabel:"Delete"});assert.equal(events[0].detail.dialogTag,FORM_DIALOG_TAG);assert.equal(events[1].detail.dialogTag,CONFIRM_DIALOG_TAG);assert.ok(events.every(event=>event.bubbles&&event.composed));});
test("native form dialogs no longer post-process collapsible sections",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/native-form-dialog.js",import.meta.url),"utf8");assert.match(source,/controller\.typographyStyles\(\)/);assert.doesNotMatch(source,/dialogLayoutStyles|prepareDetails|details-toggle/);});
test("native editor actions use the same adaptive-dialog footer as the viewer",()=>{const html=formDialogFooterHtml();assert.match(html,/ha-dialog-footer slot="footer"/);assert.match(html,/ha-button class="save" slot="primaryAction" variant="brand"/);assert.doesNotMatch(html,/<button/);});
test("native form source renders its footer directly without a legacy inline save action",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/native-form-dialog.js",import.meta.url),"utf8");assert.doesNotMatch(source,/mountFooter|inlineSave|class="actions"|class="primary"/);assert.match(source,/\$\{formDialogFooterHtml\(\)\}<\/ha-adaptive-dialog>/);});
test("frontend shells no longer contain legacy dialog placeholders",()=>{for(const file of ["main.js","task-list.js","dashboard-card.js"]){const source=readFileSync(new URL(`../../custom_components/home_tasker/frontend/${file}`,import.meta.url),"utf8");assert.doesNotMatch(source,/class="dialogs"|class="overlay"|modal-header|modal-close/);}});
test("attachment rows use the full filename in the flexible first column",()=>{const controller=Object.create(HomeTaskerBase.prototype);controller.signedFiles=new Map([["file","/signed/file"]]);const html=controller.fileLink({id:"file",filename:"a very long filename.pdf"});assert.match(html,/<a class="filename file-open" data-file-open="file" href="\/signed\/file"[^>]*>a very long filename\.pdf<\/a>/);assert.match(html,/overflow-wrap:anywhere/);assert.doesNotMatch(html,/filename-base|filename-extension|text-overflow|target="_blank"|<button/);assert.equal(EDITOR_FILE_GRID,"display:grid;grid-template-columns:minmax(0,1fr) max-content 32px;gap:8px;align-items:center;padding:4px 0");});
test("viewer and editor file rows are 40px high with compact close actions",()=>{const controller={attachments:[{id:"file",task_id:"task",size:1024}],fileLink:()=>"<a>filename.pdf</a>",size:()=>"1 KB"},task={id:"task"};const viewer=taskFilesBoxHtml(controller,task),editor=taskFilesBoxHtml(controller,task,{editable:true});assert.match(viewer,/grid-template-columns:minmax\(0,1fr\) max-content[^>]+min-height:40px/);assert.match(editor,/grid-template-columns:minmax\(0,1fr\) max-content 32px/);assert.match(editor,/padding:4px 0/);assert.match(editor,/--ha-icon-button-size:32px/);assert.match(editor,/mdi:close/);assert.match(viewer,/class="file-size" style="justify-self:end;white-space:nowrap"/);});
test("dialog expansion panels suppress Home Assistant's click fill via its own variable",()=>{for(const file of ["native-task-dialog.js","native-form-dialog.js","native-settings-dialog.js"]){const source=readFileSync(new URL(`../../custom_components/home_tasker/frontend/${file}`,import.meta.url),"utf8");assert.match(source,/ha-expansion-panel\{--input-fill-color:transparent\}/);}});
test("editable files expose a reliable full drop area with a native HA button",()=>{const controller={attachments:[],fileLink:()=>"",size:()=>""},html=taskFilesBoxHtml(controller,{id:"task"},{editable:true});assert.match(html,/class="attachment-drop-zone"/);assert.match(html,/<input type="file" multiple hidden>/);assert.match(html,/<ha-button class="choose-files" size="s" appearance="filled">/);assert.match(html,/Select file[\s\S]*Or drop your file here/);assert.doesNotMatch(html,/ha-file-upload/);const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/task-editor.js",import.meta.url),"utf8");assert.match(source,/dropZone\.ondrop/);assert.match(source,/event\.dataTransfer\.files/);});
test("history uses the same compact close action as files",()=>{const controller=Object.create(HomeTaskerBase.prototype);controller.locale=()=>"en";controller.historyTime=()=>"12:00";controller.date=value=>value;const html=controller.historyRow({id:"entry",completion_date:"2026-07-22",user_name:"User"},true);assert.match(html,/grid-template-columns:[^>]+ 32px/);assert.match(html,/--ha-icon-button-size:32px/);assert.match(html,/mdi:close/);});
test("shared file and history boxes expose destructive controls only in editor mode",()=>{const controller={attachments:[{id:"file",task_id:"task",filename:"file.txt",size:4}],fileLink:()=>"<a>file</a>",size:()=>"4 B",historyRow:(_entry,editable)=>`<span>${editable}</span>`},task={id:"task"};assert.doesNotMatch(taskFilesBoxHtml(controller,task),/class="editor-action/);assert.match(taskFilesBoxHtml(controller,task,{editable:true}),/class="editor-action remove danger"/);assert.doesNotMatch(taskHistoryBoxHtml(controller,[{id:"history"}]),/>true</);assert.match(taskHistoryBoxHtml(controller,[{id:"history"}],{editable:true}),/>true</);});
test("planning interval uses an equal-height theme-aware stepper",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/task-editor.js",import.meta.url),"utf8");assert.match(source,/mountIntervalStepper\(field\)/);assert.match(source,/schedule-select,.interval-stepper\{[^}]*height:44px/);assert.match(source,/task\.interval_decrease/);assert.match(source,/task\.interval_increase/);assert.match(source,/ha-color-fill-neutral-quiet-hover/);assert.match(source,/event\.key==="ArrowUp"/);assert.match(source,/event\.key==="ArrowDown"/);});
test("optional start date supports direct iOS input and the desktop picker API",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/task-editor.js",import.meta.url),"utf8");assert.match(source,/startTrigger=document\.createElement\("label"\)/);assert.match(source,/startInput\.style\.cssText="position:absolute;inset:0;width:100%;height:100%/);assert.match(source,/startTrigger\.append\(startText,startInput\)/);assert.match(source,/startInput\.addEventListener\("click",\(\)=>\{try\{startInput\.showPicker\?\.\(\)/);assert.doesNotMatch(source,/startInput\.click\(\)/);});
test("optional start date exposes only the native picker action",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/task-editor.js",import.meta.url),"utf8");assert.match(source,/startBox\.querySelector\("\.start-date-actions"\)\.append\(startTrigger\)/);assert.doesNotMatch(source,/append\(startTrigger,startClear\)/);});
test("planning keeps the loaded due preview visible during recalculation",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/task-editor.js",import.meta.url),"utf8");assert.match(source,/if\(!summary\.dataset\.ready\)\{summary\.innerHTML=/);assert.match(source,/summary\.dataset\.ready="true"/);assert.match(source,/summary\.setAttribute\("aria-busy","true"\)/);assert.match(source,/request===previewRequest/);});
test("attachments open through a native dialog with media previews and download fallback",()=>{let event;const dispatcher={dispatchEvent:value=>{event=value;}};const file={id:"file",filename:"photo.jpg",content_type:"image/jpeg"};showAttachmentDialog(dispatcher,file,"/signed/file");assert.equal(event.type,"show-dialog");assert.equal(event.detail.dialogTag,ATTACHMENT_DIALOG_TAG);assert.equal(event.detail.dialogParams.file,file);assert.match(attachmentPreviewHtml(file,"/signed/file"),/<img /);assert.match(attachmentPreviewHtml({...file,content_type:"video/mp4"},"/signed/file"),/<video /);assert.match(attachmentPreviewHtml({...file,content_type:"audio/mpeg"},"/signed/file"),/<audio /);assert.match(attachmentPreviewHtml({...file,content_type:"application\/pdf"},"/signed/file"),/<iframe /);const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/native-attachment-dialog.js",import.meta.url),"utf8");assert.match(source,/ha-adaptive-dialog/);assert.match(source,/attachment\.download/);});
test("task and group editor popups no longer expose delete actions",()=>{assert.equal(typeof HomeTaskerBase.prototype.mountTaskActions,"undefined");assert.equal(typeof HomeTaskerBase.prototype.mountGroupActions,"undefined");});
test("dashboard add action uses the native full-width HA button",()=>{const html=dashboardCardBodyHtml('<div class="task-row"></div>',true);assert.ok(html.indexOf("add-task")<html.indexOf("task-row"));assert.match(html,/<ha-button class="add-task" appearance="plain">/);assert.match(html,/<ha-icon slot="start" icon="mdi:plus">/);const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/\.add-task\{width:100%\}/);assert.doesNotMatch(source,/\.add-task[^}]*border:|\.add-task:hover|card-actions/);});
test("dashboard card is always frameless and its contents use the full width",()=>{const html=dashboardCardBodyHtml("",false);assert.match(html,/--ha-card-border-width:0px/);assert.match(html,/--ha-card-border-color:transparent/);assert.match(html,/border:none!important;background:transparent!important;box-shadow:none!important/);const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/\.card-content\{display:grid;gap:8px;padding:0\}/);assert.doesNotMatch(source,/name="hide_card_background"|card\.hide_background/);});
test("frameless cards retain borders around each task tile",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/\.task-row\{border-color:var\(--divider-color\)\}/);});
test("dashboard custom elements are guarded global registrations",()=>{const source=readFileSync(new URL("../../custom_components/home_tasker/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/if\(!customElements\.get\("home-tasker-card"\)\)customElements\.define/);assert.match(source,/if\(!customElements\.get\("home-tasker-card-editor"\)\)customElements\.define/);assert.doesNotMatch(source,/browser_mod/i);});
test("row menu deletion relies on the shared change event after the mutation",async()=>{const controller=Object.create(HomeTaskerBase.prototype),messages=[];controller.confirmAction=async()=>true;controller.ws=async message=>messages.push(message);let loads=0;controller.load=async()=>{loads++;};await controller.deleteTask({id:"task",name:"Task"});assert.deepEqual(messages,[{type:"home_tasker/task/delete",task_id:"task"}]);assert.equal(loads,0);});
