// Formatting helpers (dates, sizes, schedule text). Assigned to the panel
// prototype in panel.js, so `this` is the HomeTaskerPanel instance.
export function locale(){return this._hass?.locale?.language||navigator.language||"de-CH";}
export function date(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");return m?new Date(+m[1],+m[2]-1,+m[3]).toLocaleDateString(this.locale()):v;}
export function dueDateParts(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");if(!m)return {weekday:"",date:String(v||"")};const value=new Date(+m[1],+m[2]-1,+m[3]),locale=this.locale();return {weekday:value.toLocaleDateString(locale,{weekday:"long"}),date:value.toLocaleDateString(locale,{year:"numeric",month:"2-digit",day:"2-digit"})};}
export function dueDate(v){const parts=this.dueDateParts(v);return [parts.weekday,parts.date].filter(Boolean).join(" ");}
export function relativeDate(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||""),base=/^(\d{4})-(\d{2})-(\d{2})/.exec(this.today||"");if(!m||!base)return v;const target=Date.UTC(+m[1],+m[2]-1,+m[3]),today=Date.UTC(+base[1],+base[2]-1,+base[3]),days=Math.round((target-today)/86400000),absolute=Math.abs(days);let value=days,unit="day";if(absolute>=730){value=Math.round(days/365.2425);unit="year";}else if(absolute>=60){value=Math.round(days/30.4375);unit="month";}else if(absolute>=14){value=Math.round(days/7);unit="week";}return new Intl.RelativeTimeFormat("de",{numeric:"auto"}).format(value,unit);}
export function size(n){return n<1024?`${n} B`:n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;}
export function historyTime(entry){const value=entry.recorded_at?new Date(entry.recorded_at):null;return value&&!Number.isNaN(value.getTime())?value.toLocaleTimeString("de-CH",{hour:"2-digit",minute:"2-digit"}):"–";}
export function scheduleText(task){const interval=Math.max(1,Number(task.interval)||1),fixed=task.recurrence_mode==="fixed",frequency=task.frequency||"monthly",next=task.due_date?`\nFälligkeit: ${this.date(task.due_date)}`:"";if(!fixed){const singular={daily:"jeden Tag",weekly:"jede Woche",monthly:"jeden Monat",yearly:"jedes Jahr"}[frequency],plural={daily:"Tage",weekly:"Wochen",monthly:"Monate",yearly:"Jahre"}[frequency];return `${interval===1?`Findet ${singular}`:`Findet alle ${interval} ${plural}`} nach der Erledigung statt.${next}`;}if(frequency==="daily")return `${interval===1?"Findet jeden Tag statt.":`Findet alle ${interval} Tage statt.`}${next}`;if(frequency==="weekly"){const names=["Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag","Sonntag"],days=(task.weekdays||[]).map(day=>names[Number(day)]).filter(Boolean),when=days.length?` am ${days.join(", ").replace(/, ([^,]*)$/," und $1")}`:"";return `${interval===1?"Findet jede Woche":`Findet alle ${interval} Wochen`}${when} statt.${next}`;}const day=task.day_of_month==="last"?"am letzten Tag":`am ${Number(task.day_of_month)}.`;if(frequency==="yearly"){const month=new Intl.DateTimeFormat("de-CH",{month:"long"}).format(new Date(2024,Number(task.month_of_year||1)-1,1)),annualDay=task.day_of_month==="last"?`am letzten Tag im ${month}`:`am ${Number(task.day_of_month)}. ${month}`;return `${interval===1?"Findet jedes Jahr":`Findet alle ${interval} Jahre`} ${annualDay} statt.${next}`;}return `${interval===1?"Findet jeden Monat":`Findet alle ${interval} Monate`} ${day} statt.${next}`;}
