// Main list view: groups, task rows and their wiring. Assigned to the panel
// prototype in panel.js, so `this` is the HomeTaskerPanel instance.
import { esc, L, VERSION, STYLE_LINK } from "./utils.js";

export function render(){
  if(!this.shadowRoot.querySelector(".app")) this.shadowRoot.innerHTML=`${STYLE_LINK}<div class="app"></div><div class="dialogs"></div>`;
  const app=this.shadowRoot.querySelector(".app");
  app.innerHTML=`<main><header><div><h1>Home Tasker</h1><p>Wiederkehrende Aufgaben im Blick behalten</p></div></header>
    <nav><i></i><button class="link expand">${this.groups.every(g=>this.expanded.has(g.id))?"Alle zuklappen":"Alle aufklappen"}</button><select class="sort"><option value="name">Name</option><option value="due">Fälligkeit</option></select></nav>
    <section>${this.sorted().map(g=>this.groupRow(g)).join("")}</section><button class="floating-add">${L.addTask}</button><small class="version">v${VERSION}</small></main>`;
  app.querySelector(".sort").value=this.sort;
  app.querySelector(".expand").onclick=()=>{ const all=this.groups.every(g=>this.expanded.has(g.id)); this.expanded=all?new Set():new Set(this.groups.map(g=>g.id)); this.render(); };
  app.querySelector(".sort").onchange=e=>{this.sort=e.target.value;this.render();};
  app.querySelector(".floating-add").onclick=()=>this.taskEditor(null);
  app.querySelectorAll(".group").forEach(el=>this.wireGroup(el));
}
export function groupRow(g){ const shown=this.sortedTasks(this.tasksOf(g.id)), open=this.expanded.has(g.id), due=shown.filter(t=>this.due(t)).length;
  return `<article class="group" data-group="${g.id}"><div class="group-head" role="button" tabindex="0"><ha-icon class="chevron" icon="mdi:chevron-${open?"down":"right"}"></ha-icon><strong>${esc(g.name)}</strong>${due?`<span class="pill open-count">${due}</span>`:""}<i></i><button class="edit-group icon" aria-label="Gruppe bearbeiten" title="Gruppe bearbeiten"><ha-icon icon="mdi:pencil"></ha-icon></button></div>${open?`<div class="tasks">${shown.map(t=>this.taskRow(t)).join("")}</div>`:""}</article>`; }
export function fileNameParts(filename){const name=String(filename||""),dot=name.lastIndexOf(".");return dot>0&&dot<name.length-1?{base:name.slice(0,dot),extension:name.slice(dot)}:{base:name,extension:""};}
export function filePill(file){const name=String(file.filename||""),parts=this.fileNameParts(name),url=this.signedFiles.get(file.id),content=`<span style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(parts.base)}</span><span style="flex:none;white-space:nowrap">${esc(parts.extension)}</span>`,style="display:inline-flex;align-items:center;max-width:160px;min-width:0;color:var(--primary-color);text-decoration:none";return url?`<a class="pill file-pill" href="${esc(url)}" target="_blank" rel="noopener noreferrer" title="${esc(name)}" style="${style}">${content}</a>`:`<span class="pill file-pill" title="${esc(name)}" style="${style}">${content}</span>`;}
export function taskRow(t){ const files=this.attachments.filter(a=>a.task_id===t.id),assignee=this.users.find(user=>user.id===t.assignee_user_id),filePills=files.map(file=>this.filePill(file)).join("");return `<div class="task" data-task="${t.id}" tabindex="0" style="display:grid;grid-template-columns:minmax(0,1fr) 44px;align-items:center;gap:4px;padding:5px 6px 7px 10px"><div class="task-body" style="display:block;min-width:0"><strong>${esc(t.name)}</strong><div class="pills" style="display:flex;gap:6px;flex-wrap:wrap;align-items:center"><span class="pill due-date ${this.due(t)?"due":"ok"}" title="${esc(this.date(t.due_date))}">${esc(this.relativeDate(t.due_date))}</span>${assignee?`<span class="pill">${esc(assignee.name)}</span>`:""}</div>${filePills?`<div class="pills" style="display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin-top:6px">${filePills}</div>`:""}</div><button type="button" class="edit-task-row icon" aria-label="Task bearbeiten" title="Task bearbeiten" style="display:flex;align-items:center;justify-content:center;width:44px;height:44px;padding:0;color:var(--primary-color,#03a9f4)"><ha-icon icon="mdi:pencil"></ha-icon></button></div>`; }
export function wireGroup(el){ const g=this.groups.find(x=>x.id===el.dataset.group),head=el.querySelector(".group-head"),toggle=()=>{this.expanded.has(g.id)?this.expanded.delete(g.id):this.expanded.add(g.id);this.render();};head.onclick=toggle;head.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")toggle();};const edit=el.querySelector(".edit-group");edit.onclick=e=>{e.stopPropagation();this.groupEditor(g);};el.querySelectorAll("[data-task]").forEach(row=>{const t=this.tasks.find(x=>x.id===row.dataset.task),editTask=row.querySelector(".edit-task-row");row.onclick=()=>this.taskViewer(t);row.onkeydown=e=>{if(e.target===row&&(e.key==="Enter"||e.key===" "))this.taskViewer(t);};row.querySelectorAll(".file-pill").forEach(file=>file.onclick=e=>e.stopPropagation());editTask.onclick=e=>{e.stopPropagation();this.taskEditor(g.id,t);};}); }
