import { esc } from "./shared.js";
import { withStyles } from "./styles.js";
import { withTaskList } from "./task-list.js";
import { withTaskViewer } from "./task-viewer.js";
import { withGroupEditor } from "./group-editor.js";
import { withTaskEditor } from "./task-editor.js";
import { withDialogs } from "./dialogs.js";
import { closeRowActionMenu, openRowActionMenu } from "./action-menu.js";
import { showAttachmentDialog } from "./native-attachment-dialog.js";
import { showSettingsDialog } from "./native-settings-dialog.js";
import { historyNote, locale as activeLocale, setLanguage, t } from "./localize.js";

export class HomeTaskerBase extends withDialogs(withTaskEditor(withGroupEditor(withTaskViewer(withTaskList(withStyles(HTMLElement)))))) {
  constructor(){ super(); this.attachShadow({mode:"open"}); this.groups=[]; this.tasks=[]; this.attachments=[]; this.users=[]; this.tags=[]; this.today=""; this.signedFiles=new Map(); this.expanded=new Set(); this.sort="name"; this.loading=false; this.reloadPending=false; this.eventUnsubscribe=null; this.eventSubscriptionToken=0; this.detailsObserver=new MutationObserver(()=>this.prepareDetails());this.detailsObserver.observe(this.shadowRoot,{childList:true,subtree:true}); }
  connectedCallback(){this.subscribeEvents();}
  disconnectedCallback(){this.unsubscribeEvents();}
  set hass(value){if(this._hass?.connection!==value?.connection)this.unsubscribeEvents();this._hass=value;this.subscribeEvents();setLanguage(value?.locale?.language).then(changed=>{if(!this.loaded){this.loaded=true;this.load();}else if(changed)this.render();});}
  async subscribeEvents(){if(this.eventUnsubscribe||!this._hass?.connection)return;const token=++this.eventSubscriptionToken,unsubscribe=await this._hass.connection.subscribeEvents(()=>this.load(),"home_tasker_event");if(token===this.eventSubscriptionToken)this.eventUnsubscribe=unsubscribe;else unsubscribe();}
  unsubscribeEvents(){this.eventSubscriptionToken++;this.eventUnsubscribe?.();this.eventUnsubscribe=null;}
  t(key,variables){return t(key,variables);}
  async ws(msg){ return this._hass.connection.sendMessagePromise(msg); }
  async load(){if(!this._hass)return;if(this.loading){this.reloadPending=true;return;}this.loading=true;try{const [d,tags]=await Promise.all([this.ws({type:"home_tasker/list"}),this.ws({type:"tag/list"}).catch(()=>[])]);this.groups=d.groups||[];this.tasks=d.tasks||[];this.attachments=d.attachments||[];this.users=d.users||[];this.tags=Array.isArray(tags)?tags:[];this.today=d.today||"";this.signedFiles=new Map(Object.entries(d.signed_files||{}));this.render();}catch(err){if(!this.shadowRoot.querySelector(".app"))this.shadowRoot.innerHTML=`${this.styles()}<div class="app"><main><h1>Home Tasker</h1><p>${esc(t("panel.load_failed"))}</p></main></div>`;console.error("Home Tasker load failed",err);}finally{this.loading=false;if(this.reloadPending){this.reloadPending=false;void this.load();}}}
  scheduleText(task){const interval=Math.max(1,Number(task.interval)||1),fixed=task.recurrence_mode==="fixed",frequency=task.frequency||"monthly",next=task.due_date?`\n${t("task.due")}: ${this.date(task.due_date)}`:"",periodKey={daily:"day",weekly:"week",monthly:"month",yearly:"year"}[frequency]||"month",singular=t(`schedule.period_${periodKey}`),plural=t(`schedule.period_${periodKey}s`);if(!fixed)return `${t(interval===1?"schedule.after_completion_one":"schedule.after_completion_many",{interval,period:interval===1?singular:plural})}${next}`;if(frequency==="daily")return `${t(interval===1?"schedule.fixed_one":"schedule.fixed_many",{interval,period:interval===1?singular:plural})}${next}`;if(frequency==="weekly"){const formatter=new Intl.DateTimeFormat(this.locale(),{weekday:"long",timeZone:"UTC"}),names=Array.from({length:7},(_,index)=>formatter.format(new Date(Date.UTC(2024,0,index+1)))),days=(task.weekdays||[]).map(day=>names[Number(day)]).filter(Boolean),joined=days.length>1?`${days.slice(0,-1).join(", ")}${t("schedule.and")}${days.at(-1)}`:days[0]||"",when=joined?t("schedule.on_days",{days:joined}):"";return `${t(interval===1?"schedule.weekly_one":"schedule.weekly_many",{interval,days:when})}${next}`;}const day=task.day_of_month==="last"?t("schedule.on_last_day"):t("schedule.on_day_number",{day:Number(task.day_of_month)});if(frequency==="yearly"){const month=new Intl.DateTimeFormat(this.locale(),{month:"long"}).format(new Date(2024,Number(task.month_of_year||1)-1,1)),annualDay=t(task.day_of_month==="last"?"schedule.on_last_day_of_month":"schedule.on_day_of_month",{day:Number(task.day_of_month),month});return `${t(interval===1?"schedule.yearly_one":"schedule.yearly_many",{interval,day:annualDay})}${next}`;}return `${t(interval===1?"schedule.monthly_one":"schedule.monthly_many",{interval,day})}${next}`;}
  editorScheduleHtml(task,dueDates=[],status=""){const rule=esc(this.scheduleText(task).split("\n")[0]),rows=dueDates.map(due=>{const parts=this.dueDateParts(due);return `<div role="row" style="display:contents"><span role="cell">${esc(parts.weekday)}</span><span role="cell">${esc(parts.date)}</span></div>`;}).join("");return `<div>${rule}</div>${rows?`<div role="table" aria-label="${esc(t("task.due_dates"))}" style="display:grid;grid-template-columns:max-content max-content;column-gap:12px;justify-content:start;margin-top:8px">${rows}</div>`:status?`<div style="margin-top:8px">${esc(status)}</div>`:""}`;}
  historyTime(entry){const value=entry.recorded_at?new Date(entry.recorded_at):null;return value&&!Number.isNaN(value.getTime())?value.toLocaleTimeString(this.locale(),{hour:"2-digit",minute:"2-digit"}):"–";}
  historyRow(entry,deletable=false){return `<div class="detail-row history-entry ht-content" data-history="${entry.id}" style="display:grid;grid-template-columns:max-content max-content max-content minmax(0,1fr)${deletable?" 44px":""};gap:8px;align-items:start"><span title="${esc(t("history.date"))}">${this.date(entry.completion_date)}</span><span title="${esc(t("history.time"))}">${this.historyTime(entry)}</span><span title="${esc(t("history.user"))}">${esc(entry.user_name||t("common.system"))}</span><span title="${esc(t("history.notes"))}" style="min-width:0;white-space:pre-wrap;overflow-wrap:anywhere">${entry.notes?esc(historyNote(entry.notes)):"–"}</span>${deletable?`<button type="button" class="editor-action remove danger" aria-label="${esc(t("history.remove"))}" title="${esc(t("common.remove"))}" style="justify-self:end"><ha-icon icon="mdi:delete"></ha-icon></button>`:""}</div>`;}
  actionMenu(anchor,edit,remove){openRowActionMenu(this,anchor,{edit,remove});}
  closeActionMenu(){closeRowActionMenu(this);}
  async deleteTask(task){if(!await this.confirmAction(t("task.delete_title"),t("task.delete_confirm",{name:task.name}),t("common.delete"),"danger"))return;await this.ws({type:"home_tasker/task/delete",task_id:task.id});}
  async deleteGroup(group){if(!await this.confirmAction(t("group.delete_title"),t("group.delete_confirm",{name:group.name}),t("common.delete"),"danger"))return false;await this.ws({type:"home_tasker/group/delete",group_id:group.id});return true;}
  fileNameParts(filename){const name=String(filename||""),dot=name.lastIndexOf(".");return dot>0&&dot<name.length-1?{base:name.slice(0,dot),extension:name.slice(dot)}:{base:name,extension:""};}
  fileLink(file){const rawName=String(file.filename||""),name=esc(rawName),parts=this.fileNameParts(rawName),url=this.signedFiles.get(file.id),content=`<span class="filename-base" style="flex:0 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(parts.base)}</span><span class="filename-extension" style="flex:none;white-space:nowrap">${esc(parts.extension)}</span>`,style="min-width:0;max-width:100%;overflow:hidden;display:flex;white-space:nowrap;text-decoration:none";return url?`<a class="filename file-open" data-file-open="${esc(file.id)}" href="${esc(url)}" title="${name}" style="${style};min-height:0;padding:0;border:0;background:transparent;text-align:left">${content}</a>`:`<span class="filename" title="${name}" style="${style}">${content}</span>`;}
  openAttachment(file,dispatcher=this){const url=this.signedFiles.get(file.id);if(url)showAttachmentDialog(dispatcher,file,url);}
  wireFileOpeners(root,dispatcher=this){root.querySelectorAll("[data-file-open]").forEach(link=>{link.onclick=event=>{event.preventDefault();event.stopPropagation();const file=this.attachments.find(item=>item.id===link.dataset.fileOpen);if(file)this.openAttachment(file,dispatcher);};});}
  token(){return this._hass?.auth?.data?.access_token||null;} async upload(taskId,files,onUploaded){for(const file of files){const fd=new FormData();fd.append("task_id",taskId);fd.append("file",file,file.name);const r=await fetch("/api/home_tasker/upload",{method:"POST",headers:this.token()?{authorization:`Bearer ${this.token()}`}:{},body:fd});if(!r.ok)throw new Error(t("upload.failed",{status:r.status}));const response=await r.json(),{signed_url:signUrl,...record}=response;if(!this.attachments.some(item=>item.id===record.id))this.attachments.push(record);if(signUrl)this.signedFiles.set(record.id,signUrl);if(onUploaded)onUploaded(record);}}
  settings(){showSettingsDialog(this);}
  async exportArchive(){const response=await fetch("/api/home_tasker/archive",{headers:this.token()?{authorization:`Bearer ${this.token()}`}:{}});if(!response.ok)throw new Error(await response.text()||String(response.status));const blob=await response.blob(),link=document.createElement("a"),date=new Date().toISOString().slice(0,10);link.href=URL.createObjectURL(blob);link.download=`home-tasker-${date}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);}
  async importArchive(file){const response=await fetch("/api/home_tasker/archive",{method:"POST",headers:{...(this.token()?{authorization:`Bearer ${this.token()}`}:{}) ,"Content-Type":"application/zip"},body:file});if(!response.ok)throw new Error(await response.text()||String(response.status));}
  locale(){return this._hass?.locale?.language||activeLocale()||navigator.language||"en";}
  date(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");return m?new Date(+m[1],+m[2]-1,+m[3]).toLocaleDateString(this.locale()):v;}
  dueDateParts(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");if(!m)return {weekday:"",date:String(v||"")};const value=new Date(+m[1],+m[2]-1,+m[3]),locale=this.locale();return {weekday:value.toLocaleDateString(locale,{weekday:"long"}),date:value.toLocaleDateString(locale,{year:"numeric",month:"2-digit",day:"2-digit"})};}
  dueDate(v){const parts=this.dueDateParts(v);return [parts.weekday,parts.date].filter(Boolean).join(" ");}
  relativeDate(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||""),base=/^(\d{4})-(\d{2})-(\d{2})/.exec(this.today||"");if(!m||!base)return v;const target=Date.UTC(+m[1],+m[2]-1,+m[3]),today=Date.UTC(+base[1],+base[2]-1,+base[3]),days=Math.round((target-today)/86400000),absolute=Math.abs(days);let value=days,unit="day";if(absolute>=730){value=Math.round(days/365.2425);unit="year";}else if(absolute>=60){value=Math.round(days/30.4375);unit="month";}else if(absolute>=14){value=Math.round(days/7);unit="week";}return new Intl.RelativeTimeFormat(this.locale(),{numeric:"auto"}).format(value,unit);}
  size(n){return n<1024?`${n} B`:n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;}
}

export class HomeTaskerPanel extends HomeTaskerBase {}
