import { esc } from "./shared.js";
import { withStyles } from "./styles.js";
import { withTaskList } from "./task-list.js";
import { withTaskViewer } from "./task-viewer.js";
import { withGroupEditor } from "./group-editor.js";
import { withTaskEditor } from "./task-editor.js";
import { withDialogs } from "./dialogs.js";
import { closeRowActionMenu, openRowActionMenu } from "./action-menu.js";

export class HomeTaskerBase extends withDialogs(withTaskEditor(withGroupEditor(withTaskViewer(withTaskList(withStyles(HTMLElement)))))) {
  constructor(){ super(); this.attachShadow({mode:"open"}); this.groups=[]; this.tasks=[]; this.attachments=[]; this.users=[]; this.today=""; this.signedFiles=new Map(); this.expanded=new Set(); this.sort="name"; this.loading=false; this.refreshTimer=null; this.detailsObserver=new MutationObserver(()=>this.prepareDetails());this.detailsObserver.observe(this.shadowRoot,{childList:true,subtree:true}); }
  connectedCallback(){if(!this.refreshTimer)this.refreshTimer=setInterval(()=>{if(document.visibilityState==="visible")this.load();},30000);}
  disconnectedCallback(){clearInterval(this.refreshTimer);this.refreshTimer=null;}
  set hass(value){ this._hass=value; if(!this.loaded){ this.loaded=true; this.load(); } }
  async ws(msg){ return this._hass.connection.sendMessagePromise(msg); }
  async load(){if(!this._hass||this.loading)return;this.loading=true;try{const d=await this.ws({type:"home_tasker/list"});this.groups=d.groups||[];this.tasks=d.tasks||[];this.attachments=d.attachments||[];this.users=d.users||[];this.today=d.today||"";this.signedFiles=new Map(Object.entries(d.signed_files||{}));this.render();}catch(err){if(!this.shadowRoot.querySelector(".app"))this.shadowRoot.innerHTML=`${this.styles()}<div class="app"><main><h1>Home Tasker</h1><p>Die Daten konnten nicht geladen werden. Ein neuer Versuch folgt automatisch.</p></main></div><div class="dialogs"></div>`;console.error("Home Tasker load failed",err);}finally{this.loading=false;}}
  async signFiles(){const result=await this.ws({type:"home_tasker/attachment/sign_all"});this.signedFiles=new Map(Object.entries(result.urls||{}));}
  scheduleText(task){const interval=Math.max(1,Number(task.interval)||1),fixed=task.recurrence_mode==="fixed",frequency=task.frequency||"monthly",next=task.due_date?`\nFälligkeit: ${this.date(task.due_date)}`:"";if(!fixed){const singular={daily:"jeden Tag",weekly:"jede Woche",monthly:"jeden Monat",yearly:"jedes Jahr"}[frequency],plural={daily:"Tage",weekly:"Wochen",monthly:"Monate",yearly:"Jahre"}[frequency];return `${interval===1?`Findet ${singular}`:`Findet alle ${interval} ${plural}`} nach der Erledigung statt.${next}`;}if(frequency==="daily")return `${interval===1?"Findet jeden Tag statt.":`Findet alle ${interval} Tage statt.`}${next}`;if(frequency==="weekly"){const names=["Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag","Sonntag"],days=(task.weekdays||[]).map(day=>names[Number(day)]).filter(Boolean),when=days.length?` am ${days.join(", ").replace(/, ([^,]*)$/," und $1")}`:"";return `${interval===1?"Findet jede Woche":`Findet alle ${interval} Wochen`}${when} statt.${next}`;}const day=task.day_of_month==="last"?"am letzten Tag":`am ${Number(task.day_of_month)}.`;if(frequency==="yearly"){const month=new Intl.DateTimeFormat("de-CH",{month:"long"}).format(new Date(2024,Number(task.month_of_year||1)-1,1)),annualDay=task.day_of_month==="last"?`am letzten Tag im ${month}`:`am ${Number(task.day_of_month)}. ${month}`;return `${interval===1?"Findet jedes Jahr":`Findet alle ${interval} Jahre`} ${annualDay} statt.${next}`;}return `${interval===1?"Findet jeden Monat":`Findet alle ${interval} Monate`} ${day} statt.${next}`;}
  editorScheduleHtml(task,dueDates=[],status=""){const rule=esc(this.scheduleText(task).split("\n")[0]),rows=dueDates.map(due=>{const parts=this.dueDateParts(due);return `<div role="row" style="display:contents"><span role="cell">${esc(parts.weekday)}</span><span role="cell">${esc(parts.date)}</span></div>`;}).join("");return `<div>${rule}</div>${rows?`<div role="table" aria-label="Fälligkeiten" style="display:grid;grid-template-columns:max-content max-content;column-gap:12px;justify-content:start;margin-top:8px">${rows}</div>`:status?`<div style="margin-top:8px">${esc(status)}</div>`:""}`;}
  historyTime(entry){const value=entry.recorded_at?new Date(entry.recorded_at):null;return value&&!Number.isNaN(value.getTime())?value.toLocaleTimeString("de-CH",{hour:"2-digit",minute:"2-digit"}):"–";}
  historyRow(entry,deletable=false){return `<div class="detail-row history-entry" data-history="${entry.id}" style="display:grid;grid-template-columns:max-content max-content max-content minmax(0,1fr)${deletable?" 44px":""};gap:8px;align-items:start"><span title="Datum">${this.date(entry.completion_date)}</span><span title="Zeit">${this.historyTime(entry)}</span><span title="Benutzer">${esc(entry.user_name||"system")}</span><span title="Notizen" style="min-width:0;white-space:pre-wrap;overflow-wrap:anywhere">${entry.notes?esc(entry.notes):"–"}</span>${deletable?'<button type="button" class="editor-action remove danger" aria-label="Verlaufseintrag entfernen" title="Entfernen" style="justify-self:end"><ha-icon icon="mdi:delete"></ha-icon></button>':""}</div>`;}
  actionMenu(anchor,edit,remove){openRowActionMenu(this,anchor,{edit,remove});}
  closeActionMenu(){closeRowActionMenu(this);}
  async deleteTask(task){if(!await this.confirmAction("Task löschen",`Möchtest du den Task „${task.name}“ wirklich löschen? Dateien und Verlauf werden ebenfalls gelöscht.`,"Löschen","danger"))return;await this.ws({type:"home_tasker/task/delete",task_id:task.id});await this.load();}
  async deleteGroup(group){if(!await this.confirmAction("Gruppe löschen",`Möchtest du die Gruppe „${group.name}“ wirklich löschen? Enthaltene Tasks, Dateien und Verläufe werden ebenfalls gelöscht.`,"Löschen","danger"))return;await this.ws({type:"home_tasker/group/delete",group_id:group.id});await this.load();}
  fileNameParts(filename){const name=String(filename||""),dot=name.lastIndexOf(".");return dot>0&&dot<name.length-1?{base:name.slice(0,dot),extension:name.slice(dot)}:{base:name,extension:""};}
  fileLink(file){const rawName=String(file.filename||""),name=esc(rawName),parts=this.fileNameParts(rawName),url=this.signedFiles.get(file.id),content=`<span class="filename-base" style="flex:0 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(parts.base)}</span><span class="filename-extension" style="flex:none;white-space:nowrap">${esc(parts.extension)}</span>`,style="min-width:0;max-width:100%;overflow:hidden;display:flex;white-space:nowrap;text-decoration:none";return url?`<a class="filename" href="${esc(url)}" target="_blank" rel="noopener noreferrer" title="${name}" style="${style}">${content}</a>`:`<span class="filename" title="${name}" style="${style}">${content}</span>`;}
  token(){return this._hass?.auth?.data?.access_token||null;} async upload(taskId,files,onUploaded){for(const file of files){const fd=new FormData();fd.append("task_id",taskId);fd.append("file",file,file.name);const r=await fetch("/api/home_tasker/upload",{method:"POST",headers:this.token()?{authorization:`Bearer ${this.token()}`}:{},body:fd});if(!r.ok)throw new Error(`Upload fehlgeschlagen (${r.status})`);const record=await r.json();this.attachments.push(record);if(onUploaded)onUploaded(record);}await this.signFiles();}
  locale(){return this._hass?.locale?.language||navigator.language||"de-CH";}
  date(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");return m?new Date(+m[1],+m[2]-1,+m[3]).toLocaleDateString(this.locale()):v;}
  dueDateParts(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");if(!m)return {weekday:"",date:String(v||"")};const value=new Date(+m[1],+m[2]-1,+m[3]),locale=this.locale();return {weekday:value.toLocaleDateString(locale,{weekday:"long"}),date:value.toLocaleDateString(locale,{year:"numeric",month:"2-digit",day:"2-digit"})};}
  dueDate(v){const parts=this.dueDateParts(v);return [parts.weekday,parts.date].filter(Boolean).join(" ");}
  relativeDate(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||""),base=/^(\d{4})-(\d{2})-(\d{2})/.exec(this.today||"");if(!m||!base)return v;const target=Date.UTC(+m[1],+m[2]-1,+m[3]),today=Date.UTC(+base[1],+base[2]-1,+base[3]),days=Math.round((target-today)/86400000),absolute=Math.abs(days);let value=days,unit="day";if(absolute>=730){value=Math.round(days/365.2425);unit="year";}else if(absolute>=60){value=Math.round(days/30.4375);unit="month";}else if(absolute>=14){value=Math.round(days/7);unit="week";}return new Intl.RelativeTimeFormat("de",{numeric:"auto"}).format(value,unit);}
  size(n){return n<1024?`${n} B`:n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;}
}

export class HomeTaskerPanel extends HomeTaskerBase {}
