const VERSION = "0.2.48";
const CSS_URL = new URL(`./panel.css?v=${VERSION}`, import.meta.url).href;
const STYLE_LINK = `<link rel="stylesheet" href="${CSS_URL}">`;
const L = { addTask:"Task hinzufügen", fixed:"Nach Kalender", sliding:"Nach Erledigung", daily:"Täglich", weekly:"Wöchentlich", monthly:"Monatlich", yearly:"Jährlich", save:"Speichern", files:"Dateien", history:"Verlauf", noFiles:"Keine Dateien", noHistory:"Noch kein Verlauf" };
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
class HomeTaskerPanel extends HTMLElement {
  constructor(){ super(); this.attachShadow({mode:"open"}); this.groups=[]; this.tasks=[]; this.attachments=[]; this.users=[]; this.today=""; this.signedFiles=new Map(); this.expanded=new Set(); this.sort="name"; this.loading=false; this.refreshTimer=null; this.detailsObserver=new MutationObserver(()=>this.prepareDetails());this.detailsObserver.observe(this.shadowRoot,{childList:true,subtree:true}); }
  connectedCallback(){if(!this.refreshTimer)this.refreshTimer=setInterval(()=>{if(document.visibilityState==="visible")this.load();},30000);}
  disconnectedCallback(){clearInterval(this.refreshTimer);this.refreshTimer=null;}
  set hass(value){ this._hass=value; if(!this.loaded){ this.loaded=true; this.load(); } }
  async ws(msg){ return this._hass.connection.sendMessagePromise(msg); }
  async load(){if(!this._hass||this.loading)return;this.loading=true;try{const d=await this.ws({type:"home_tasker/list"});this.groups=d.groups||[];this.tasks=d.tasks||[];this.attachments=d.attachments||[];this.users=d.users||[];this.today=d.today||"";this.signedFiles=new Map(Object.entries(d.signed_files||{}));this.render();}catch(err){if(!this.shadowRoot.querySelector(".app"))this.shadowRoot.innerHTML=`${STYLE_LINK}<div class="app"><main><h1>Home Tasker</h1><p>Die Daten konnten nicht geladen werden. Ein neuer Versuch folgt automatisch.</p></main></div><div class="dialogs"></div>`;console.error("Home Tasker load failed",err);}finally{this.loading=false;}}
  async signFiles(){const result=await this.ws({type:"home_tasker/attachment/sign_all"});this.signedFiles=new Map(Object.entries(result.urls||{}));}
  tasksOf(id){ return this.tasks.filter(t=>t.group_id===id); }
  sortedTasks(tasks){const sorted=[...tasks];if(this.sort==="due")sorted.sort((a,b)=>a.due_date.localeCompare(b.due_date)||a.name.localeCompare(b.name,"de"));else sorted.sort((a,b)=>a.name.localeCompare(b.name,"de"));return sorted;}
  due(t){return Boolean(this.today&&t.due_date<=this.today);}
  sorted(){ const g=[...this.groups]; if(this.sort==="due"){const first=x=>this.tasksOf(x.id).reduce((date,t)=>t.due_date<date?t.due_date:date,"9999-12-31");g.sort((a,b)=>first(a).localeCompare(first(b))||a.name.localeCompare(b.name,"de"));}else g.sort((a,b)=>a.name.localeCompare(b.name,"de")); return g; }
  modalHeader(title,id){return `<div class="modal-header"><button type="button" class="modal-close" aria-label="Schließen" title="Schließen"><ha-icon icon="mdi:close"></ha-icon></button><h2${id?` id="${id}"`:""}>${title}</h2></div>`;}
  render(){
    if(!this.shadowRoot.querySelector(".app")) this.shadowRoot.innerHTML=`${STYLE_LINK}<div class="app"></div><div class="dialogs"></div>`;
    const app=this.shadowRoot.querySelector(".app");
    app.innerHTML=`<main><header><div><h1>Home Tasker</h1><p>Wiederkehrende Aufgaben im Blick behalten</p></div></header>
      <nav><i></i><button class="link expand">${this.groups.every(g=>this.expanded.has(g.id))?"Alle zuklappen":"Alle aufklappen"}</button><select class="sort"><option value="name">Name</option><option value="due">Fälligkeit</option></select></nav>
      <section>${this.sorted().map(g=>this.groupRow(g)).join("")}</section><button class="floating-add">${L.addTask}</button><small class="version">v${VERSION}</small></main>`;
    app.querySelector(".sort").value=this.sort;
    app.querySelector(".expand").onclick=()=>{ const all=this.groups.every(g=>this.expanded.has(g.id)); this.expanded=all?new Set():new Set(this.groups.map(g=>g.id)); this.render(); };
    app.querySelector(".sort").onchange=e=>{this.sort=e.target.value;this.render();};
    app.querySelector(".floating-add").onclick=()=>this.taskEditor(null);
    app.querySelectorAll(".group").forEach(el=>this.wireGroup(el));
  }
  groupRow(g){ const shown=this.sortedTasks(this.tasksOf(g.id)), open=this.expanded.has(g.id), due=shown.filter(t=>this.due(t)).length;
    return `<article class="group" data-group="${g.id}"><div class="group-head" role="button" tabindex="0"><ha-icon class="chevron" icon="mdi:chevron-${open?"down":"right"}"></ha-icon><strong>${esc(g.name)}</strong>${due?`<span class="pill open-count">${due}</span>`:""}<i></i><button class="edit-group icon" aria-label="Gruppe bearbeiten" title="Gruppe bearbeiten"><ha-icon icon="mdi:pencil"></ha-icon></button></div>${open?`<div class="tasks">${shown.map(t=>this.taskRow(t)).join("")}</div>`:""}</article>`; }
  fileNameParts(filename){const name=String(filename||""),dot=name.lastIndexOf(".");return dot>0&&dot<name.length-1?{base:name.slice(0,dot),extension:name.slice(dot)}:{base:name,extension:""};}
  filePill(file){const name=String(file.filename||""),parts=this.fileNameParts(name),url=this.signedFiles.get(file.id),content=`<span style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(parts.base)}</span><span style="flex:none;white-space:nowrap">${esc(parts.extension)}</span>`,style="display:inline-flex;align-items:center;max-width:160px;min-width:0;color:var(--primary-color);text-decoration:none";return url?`<a class="pill file-pill" href="${esc(url)}" target="_blank" rel="noopener noreferrer" title="${esc(name)}" style="${style}">${content}</a>`:`<span class="pill file-pill" title="${esc(name)}" style="${style}">${content}</span>`;}
  taskRow(t){ const files=this.attachments.filter(a=>a.task_id===t.id),assignee=this.users.find(user=>user.id===t.assignee_user_id),filePills=files.map(file=>this.filePill(file)).join("");return `<div class="task" data-task="${t.id}" tabindex="0" style="display:grid;grid-template-columns:minmax(0,1fr) 44px;align-items:center;gap:4px;padding:5px 6px 7px 10px"><div class="task-body" style="display:block;min-width:0"><strong>${esc(t.name)}</strong><div class="pills" style="display:flex;gap:6px;flex-wrap:wrap;align-items:center"><span class="pill due-date ${this.due(t)?"due":"ok"}" title="${esc(this.date(t.due_date))}">${esc(this.relativeDate(t.due_date))}</span>${assignee?`<span class="pill">${esc(assignee.name)}</span>`:""}</div>${filePills?`<div class="pills" style="display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin-top:6px">${filePills}</div>`:""}</div><button type="button" class="edit-task-row icon" aria-label="Task bearbeiten" title="Task bearbeiten" style="display:flex;align-items:center;justify-content:center;width:44px;height:44px;padding:0;color:var(--primary-color,#03a9f4)"><ha-icon icon="mdi:pencil"></ha-icon></button></div>`; }
  wireGroup(el){ const g=this.groups.find(x=>x.id===el.dataset.group),head=el.querySelector(".group-head"),toggle=()=>{this.expanded.has(g.id)?this.expanded.delete(g.id):this.expanded.add(g.id);this.render();};head.onclick=toggle;head.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")toggle();};const edit=el.querySelector(".edit-group");edit.onclick=e=>{e.stopPropagation();this.groupEditor(g);};el.querySelectorAll("[data-task]").forEach(row=>{const t=this.tasks.find(x=>x.id===row.dataset.task),editTask=row.querySelector(".edit-task-row");row.onclick=()=>this.taskViewer(t);row.onkeydown=e=>{if(e.target===row&&(e.key==="Enter"||e.key===" "))this.taskViewer(t);};row.querySelectorAll(".file-pill").forEach(file=>file.onclick=e=>e.stopPropagation());editTask.onclick=e=>{e.stopPropagation();this.taskEditor(g.id,t);};}); }
  scheduleText(task){const interval=Math.max(1,Number(task.interval)||1),fixed=task.recurrence_mode==="fixed",frequency=task.frequency||"monthly",next=task.due_date?`\nFälligkeit: ${this.date(task.due_date)}`:"";if(!fixed){const singular={daily:"jeden Tag",weekly:"jede Woche",monthly:"jeden Monat",yearly:"jedes Jahr"}[frequency],plural={daily:"Tage",weekly:"Wochen",monthly:"Monate",yearly:"Jahre"}[frequency];return `${interval===1?`Findet ${singular}`:`Findet alle ${interval} ${plural}`} nach der Erledigung statt.${next}`;}if(frequency==="daily")return `${interval===1?"Findet jeden Tag statt.":`Findet alle ${interval} Tage statt.`}${next}`;if(frequency==="weekly"){const names=["Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag","Sonntag"],days=(task.weekdays||[]).map(day=>names[Number(day)]).filter(Boolean),when=days.length?` am ${days.join(", ").replace(/, ([^,]*)$/," und $1")}`:"";return `${interval===1?"Findet jede Woche":`Findet alle ${interval} Wochen`}${when} statt.${next}`;}const day=task.day_of_month==="last"?"am letzten Tag":`am ${Number(task.day_of_month)}.`;if(frequency==="yearly"){const month=new Intl.DateTimeFormat("de-CH",{month:"long"}).format(new Date(2024,Number(task.month_of_year||1)-1,1)),annualDay=task.day_of_month==="last"?`am letzten Tag im ${month}`:`am ${Number(task.day_of_month)}. ${month}`;return `${interval===1?"Findet jedes Jahr":`Findet alle ${interval} Jahre`} ${annualDay} statt.${next}`;}return `${interval===1?"Findet jeden Monat":`Findet alle ${interval} Monate`} ${day} statt.${next}`;}
  editorScheduleHtml(task,dueDates=[],status=""){const rule=esc(this.scheduleText(task).split("\n")[0]),rows=dueDates.map(due=>{const parts=this.dueDateParts(due);return `<div role="row" style="display:contents"><span role="cell">${esc(parts.weekday)}</span><span role="cell">${esc(parts.date)}</span></div>`;}).join("");return `<div>${rule}</div>${rows?`<div role="table" aria-label="Fälligkeiten" style="display:grid;grid-template-columns:max-content max-content;column-gap:12px;justify-content:start;margin-top:8px">${rows}</div>`:status?`<div style="margin-top:8px">${esc(status)}</div>`:""}`;}
  historyTime(entry){const value=entry.recorded_at?new Date(entry.recorded_at):null;return value&&!Number.isNaN(value.getTime())?value.toLocaleTimeString("de-CH",{hour:"2-digit",minute:"2-digit"}):"–";}
  historyRow(entry,deletable=false){return `<div class="detail-row history-entry" data-history="${entry.id}" style="display:grid;grid-template-columns:max-content max-content max-content minmax(0,1fr)${deletable?" 44px":""};gap:8px;align-items:start"><span title="Datum">${this.date(entry.completion_date)}</span><span title="Zeit">${this.historyTime(entry)}</span><span title="Benutzer">${esc(entry.user_name||"system")}</span><span title="Notizen" style="min-width:0;white-space:pre-wrap;overflow-wrap:anywhere">${entry.notes?esc(entry.notes):"–"}</span>${deletable?'<button type="button" class="editor-action remove danger" aria-label="Verlaufseintrag entfernen" title="Entfernen" style="justify-self:end"><ha-icon icon="mdi:delete"></ha-icon></button>':""}</div>`;}
  async taskViewer(task){
    const root=this.shadowRoot.querySelector(".dialogs"),group=this.groups.find(item=>item.id===task.group_id),assignee=this.users.find(user=>user.id===task.assignee_user_id),files=this.attachments.filter(file=>file.task_id===task.id);
    root.innerHTML=`<div class="overlay viewer-overlay"><div class="modal task-viewer" role="dialog" aria-modal="true" aria-labelledby="task-viewer-title">${this.modalHeader(esc(task.name),"task-viewer-title")}<div class="viewer-pills"><span class="pill"><ha-icon icon="mdi:devices"></ha-icon>${esc(group?.name||"Keine Gruppe")}</span><span class="pill"><ha-icon icon="mdi:account"></ha-icon>${esc(assignee?.name||"Nicht zugewiesen")}</span></div><section class="viewer-section"><h3>Beschreibung</h3><div class="viewer-description"></div></section><section class="viewer-section"><h3>Planung</h3><p>${esc(this.scheduleText(task))}</p></section><section class="details viewer-box"><h3>${L.files}</h3><div class="viewer-file-list">${files.length?files.map(file=>`<div class="detail-row">${this.fileLink(file)}<span class="file-size">${this.size(file.size)}</span></div>`).join(""):`<small>${L.noFiles}</small>`}</div></section><section class="details viewer-box"><h3>${L.history}</h3><div class="viewer-history-list">Laden…</div></section><label class="viewer-notes"><span>Notizen zur Erledigung</span><textarea placeholder="Optionale Notizen für den Verlauf"></textarea></label><div class="viewer-actions"><button type="button" class="viewer-complete"><ha-icon icon="mdi:check-circle-outline"></ha-icon><span>Erledigt</span></button></div></div></div>`;
    const description=root.querySelector(".viewer-description");if(task.description){const md=document.createElement("ha-markdown");md.breaks=true;md.content=task.description;description.appendChild(md);}else description.innerHTML="<p>Keine Beschreibung</p>";
    let closed=false;const close=()=>{if(closed)return;closed=true;window.removeEventListener("keydown",onKey);root.innerHTML="";},onKey=e=>{if(e.key==="Escape")close();};window.addEventListener("keydown",onKey);root.querySelector(".modal-close").onclick=close;root.querySelector(".viewer-overlay").onclick=e=>{if(e.target===e.currentTarget)close();};root.querySelector(".viewer-complete").onclick=async()=>{const notes=root.querySelector(".viewer-notes textarea").value.trim()||null;if(!await this.confirmAction("Task erledigen",`Möchtest du den Task „${task.name}“ als erledigt markieren?`,"Erledigen","success","mdi:check-circle-outline"))return;await this.ws({type:"home_tasker/task/complete",task_id:task.id,notes});close();await this.load();};
    try{const data=await this.ws({type:"home_tasker/history/list",task_id:task.id});if(closed)return;const history=root.querySelector(".viewer-history-list");history.innerHTML=data.history.length?data.history.map(entry=>this.historyRow(entry)).join(""):`<small>${L.noHistory}</small>`;}catch(err){if(!closed)root.querySelector(".viewer-history-list").innerHTML=`<small>Verlauf konnte nicht geladen werden: ${esc(err.message||err)}</small>`;}
  }
  groupEditor(group=null){ const g=group||{}; this.dialog(group?"Gruppe bearbeiten":"Neue Gruppe",[
    ["name","Name",g.name,true],["manufacturer","Hersteller",g.manufacturer],["model","Modell",g.model],["description","Beschreibung",g.description,false,"textarea"]
  ],async v=>{const payload={name:v.name,manufacturer:v.manufacturer||null,model:v.model||null,description:v.description||null};await this.ws({type:`home_tasker/group/${group?"update":"create"}`,...(group?{group_id:group.id}:{}),...payload});await this.load();},group?modal=>this.mountGroupActions(modal,group):null); }
  mountGroupActions(modal,group){const actions=modal.querySelector(".actions");actions.insertAdjacentHTML("afterbegin",`<button type="button" class="editor-action danger group-delete" aria-label="Gruppe löschen" title="Gruppe löschen"><ha-icon icon="mdi:delete"></ha-icon></button><i></i>`);actions.querySelector(".group-delete").onclick=async()=>{if(!await this.confirmAction("Gruppe löschen",`Möchtest du die Gruppe „${group.name}“ wirklich löschen? Enthaltene Tasks, Dateien und Verläufe werden ebenfalls gelöscht.`,"Löschen","danger","mdi:alert-outline"))return;await this.ws({type:"home_tasker/group/delete",group_id:group.id});this.shadowRoot.querySelector(".dialogs").innerHTML="";await this.load();};}
  async taskEditor(groupId,task=null){const t=task||{},selectedGroup=this.groups.find(g=>g.id===(t.group_id||groupId)),pendingFiles=new Set(),pendingHistory=new Set(),newUploads=new Set(),today=this.today,[year,month,day]=(t.due_date||today).split("-").map(Number),due=new Date(Date.UTC(year,month-1,day)),schedule={weekdays:[...(t.weekdays?.length?t.weekdays:[due.getUTCDay()===0?6:due.getUTCDay()-1])],day_of_month:t.day_of_month||day,month_of_year:t.month_of_year||month,existingDue:t.due_date||null,anchor:t.schedule_anchor||t.due_date||null};this.dialog(task?"Task bearbeiten":"Neuer Task",[
    ["group","Gruppe",selectedGroup?.name||""],["assignee_user_id","Benutzer",t.assignee_user_id||"",false,"select",[["","Nicht zugewiesen"],...this.users.map(user=>[user.id,user.name])]], ["name","Name",t.name,true],["description","Beschreibung",t.description,false,"textarea"],["start_date","Beginnt am",t.start_date||"",false,"date"],["recurrence_mode","Fälligkeit berechnen",t.recurrence_mode||"sliding",true,"select",[["fixed",L.fixed],["sliding",L.sliding]]],["frequency","Rhythmus",t.frequency||"monthly",true,"select",[["daily",L.daily],["weekly",L.weekly],["monthly",L.monthly],["yearly",L.yearly]]],["interval","Alle",t.interval||1,true,"number"]
  ],async v=>{const typed=v.group.trim(),match=this.groups.find(g=>g.name.trim().toLocaleLowerCase("de")===typed.toLocaleLowerCase("de")),group=match?{group_id:match.id}:{group_name:typed||null};for(const id of [...pendingHistory]){await this.ws({type:"home_tasker/history/delete",task_id:task.id,entry_id:id});pendingHistory.delete(id);}for(const id of [...pendingFiles]){await this.ws({type:"home_tasker/attachment/delete",attachment_id:id});pendingFiles.delete(id);}await this.ws({type:`home_tasker/task/${task?"update":"create"}`,...(task?{task_id:task.id}:{}),...group,name:v.name,description:v.description||null,assignee_user_id:v.assignee_user_id||null,start_date:v.start_date||null,recurrence_mode:v.recurrence_mode,frequency:v.frequency,interval:Number(v.interval),weekdays:schedule.weekdays,day_of_month:schedule.day_of_month,month_of_year:schedule.month_of_year});newUploads.clear();await this.load();},modal=>{this.mountGroupPicker(modal);this.arrangeSchedule(modal,schedule,Boolean(t.start_date));this.arrangeAssignment(modal);if(task){this.mountDetails(modal,task,pendingFiles,pendingHistory,newUploads);this.mountTaskActions(modal,task);}},async()=>{for(const id of newUploads){try{await this.ws({type:"home_tasker/attachment/delete",attachment_id:id});}catch{}}await this.load();});}
  mountGroupPicker(modal){const input=modal.querySelector('[name="group"]'),label=input.closest("label"),control=document.createElement("div"),results=document.createElement("div"),toggle=document.createElement("button");label.classList.add("group-combo");control.className="combo-control";results.className="combo-results";results.hidden=true;toggle.type="button";toggle.className="combo-toggle";toggle.setAttribute("aria-label","Gruppenauswahl öffnen");control.innerHTML='<ha-icon icon="mdi:magnify"></ha-icon>';input.setAttribute("autocomplete","off");input.setAttribute("role","combobox");input.setAttribute("aria-autocomplete","list");input.setAttribute("aria-expanded","false");input.placeholder="Gruppe suchen oder neu erstellen";input.before(control);control.append(input,toggle);label.append(results);const icon=()=>toggle.innerHTML=`<ha-icon icon="mdi:${input.value?"close":"chevron-down"}"></ha-icon>`,close=()=>{results.hidden=true;input.setAttribute("aria-expanded","false");icon();},render=()=>{const query=input.value.trim(),normalized=query.toLocaleLowerCase("de"),matches=[...this.groups].filter(group=>group.name.toLocaleLowerCase("de").includes(normalized)).sort((a,b)=>a.name.localeCompare(b.name,"de")),exact=this.groups.some(group=>group.name.trim().toLocaleLowerCase("de")===normalized);results.innerHTML=matches.map((group,index)=>`<button type="button" class="combo-option" data-index="${index}"><ha-icon icon="mdi:devices"></ha-icon><span>${esc(group.name)}</span></button>`).join("")+(query&&!exact?`<button type="button" class="combo-option create" data-create><ha-icon icon="mdi:plus"></ha-icon><span>„${esc(query)}“ als neue Gruppe erstellen</span></button>`:"")||'<div class="combo-empty">Keine Gruppen vorhanden</div>';results.hidden=false;input.setAttribute("aria-expanded","true");results.querySelectorAll("button").forEach(button=>{button.onmousedown=e=>e.preventDefault();button.onclick=()=>{if(!button.hasAttribute("data-create"))input.value=matches[Number(button.dataset.index)].name;close();input.focus();};});icon();};input.onfocus=render;input.oninput=render;input.onkeydown=e=>{if(e.key==="Escape"){close();input.blur();}};toggle.onclick=()=>{if(input.value){input.value="";render();input.focus();}else if(results.hidden){render();input.focus();}else close();};label.onfocusout=()=>setTimeout(()=>{if(!label.contains(this.shadowRoot.activeElement))close();},0);icon();}
  arrangeAssignment(modal){const form=modal.querySelector("form"),fields=[form.querySelector('[data-field="group"]'),form.querySelector('[data-field="assignee_user_id"]')],box=document.createElement("section"),schedule=form.querySelector(".schedule-box");box.className="details assignment-box";box.innerHTML="<h3>Zuordnung</h3>";schedule?schedule.after(box):form.insertBefore(box,fields[0]);fields.forEach(field=>box.append(field));}
  mountTaskActions(modal,task){const actions=modal.querySelector(".actions");actions.insertAdjacentHTML("afterbegin",`<button type="button" class="editor-action danger task-delete" aria-label="Task löschen" title="Task löschen"><ha-icon icon="mdi:delete"></ha-icon></button><i></i>`);actions.querySelector(".task-delete").onclick=async()=>{if(!await this.confirmAction("Task löschen",`Möchtest du den Task „${task.name}“ wirklich löschen? Dateien und Verlauf werden ebenfalls gelöscht.`,"Löschen","danger","mdi:alert-outline"))return;await this.ws({type:"home_tasker/task/delete",task_id:task.id});this.shadowRoot.querySelector(".dialogs").innerHTML="";await this.load();};}
  confirmAction(title,message,confirmLabel,tone="danger",icon="mdi:alert-outline"){return new Promise(resolve=>{const host=this.shadowRoot.querySelector(".dialogs"),layer=document.createElement("div");layer.className="confirm-layer";layer.innerHTML=`<div class="confirm-overlay"><div class="confirm-modal" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><div class="confirm-title ${tone}"><ha-icon icon="${esc(icon)}"></ha-icon><h2 id="confirm-title">${esc(title)}</h2></div><p>${esc(message)}</p><div class="confirm-actions"><button type="button" class="confirm-cancel">Abbrechen</button><button type="button" class="confirm-submit ${tone}">${esc(confirmLabel)}</button></div></div></div>`;host.append(layer);const done=value=>{window.removeEventListener("keydown",onKey);layer.remove();resolve(value);},onKey=e=>{if(e.key==="Escape")done(false);};window.addEventListener("keydown",onKey);layer.querySelector(".confirm-cancel").onclick=()=>done(false);layer.querySelector(".confirm-submit").onclick=()=>done(true);layer.querySelector(".confirm-overlay").onclick=e=>{if(e.target===e.currentTarget)done(false);};requestAnimationFrame(()=>layer.querySelector(".confirm-submit").focus());});}
  arrangeSchedule(modal,schedule,startOpen=false){
    const form=modal.querySelector("form"),start=form.querySelector('[data-field="start_date"]'),startInput=form.elements.start_date,recurrence=form.querySelector('[data-field="recurrence_mode"]'),frequency=form.querySelector('[data-field="frequency"]'),interval=form.querySelector('[data-field="interval"]'),mode=form.elements.recurrence_mode,row=document.createElement("div"),options=document.createElement("div"),preview=document.createElement("div"),summary=document.createElement("div"),more=document.createElement("button"),box=document.createElement("section"),startBox=document.createElement("section"),startTrigger=document.createElement("button"),startClear=document.createElement("button");
    row.className="interval-row";options.className="schedule-options";preview.className="due-preview-list";preview.style.cssText="display:flex;flex-direction:column;align-items:flex-start;gap:0";summary.className="schedule-summary";summary.style.cssText="margin:2px 0 0;color:var(--primary-text-color);font-size:var(--ha-font-size-m,14px);line-height:var(--ha-line-height-normal,1.4)";box.className="details schedule-box";box.style.cssText="display:flex;flex-direction:column;gap:10px";box.innerHTML="<h3>Planung</h3>";form.insertBefore(box,start);row.append(frequency,interval);box.append(recurrence,row,options);[recurrence,frequency].forEach(field=>{const title=field.querySelector(":scope>span");if(title)title.style.cssText="font-size:var(--ha-font-size-m,14px);font-weight:var(--ha-font-weight-medium,500)";});
    more.type="button";more.className="link show-more-dates";more.textContent="Zeige mehr…";more.style.cssText="padding:0;min-height:32px;font-size:var(--ha-font-size-m,14px);font-weight:var(--ha-font-weight-normal,400)";preview.innerHTML='<h3 style="font-size:var(--ha-font-size-m,14px);font-weight:var(--ha-font-weight-medium,500)">Vorschau Fälligkeiten</h3>';preview.append(summary,more);
    startBox.className="start-date-option";startBox.style.cssText="display:flex;flex-direction:column;gap:0;margin:0;padding:0";startBox.innerHTML='<h3 class="start-date-title" style="margin:0;color:var(--secondary-text-color);font-size:var(--ha-font-size-m,14px);font-weight:var(--ha-font-weight-medium,500)">Optionales Startdatum</h3><div class="start-date-actions" style="display:flex;align-items:center;gap:4px"></div>';
    start.style.cssText="position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap";startTrigger.type="button";startTrigger.className="link start-date-trigger";startTrigger.style.cssText="padding:0;min-height:32px;text-align:left;font-size:var(--ha-font-size-m,14px);font-weight:var(--ha-font-weight-normal,400)";
    startClear.type="button";startClear.className="link start-date-clear";startClear.textContent="Entfernen";startClear.style.cssText="padding:0 8px;min-height:32px;color:var(--error-color);font-size:var(--ha-font-size-m,14px);font-weight:var(--ha-font-weight-normal,400)";startBox.querySelector(".start-date-actions").append(startTrigger,startClear,start);box.append(startBox,preview);
    const days=()=>`${Array.from({length:31},(_,i)=>`<option value="${i+1}" ${String(schedule.day_of_month)===String(i+1)?"selected":""}>${i+1}</option>`).join("")}<option value="last" ${schedule.day_of_month==="last"?"selected":""}>Letzter Tag</option>`;
    let previewRequest=0,dirty=false,visibleCount=4;const updateSummary=async()=>{const task={start_date:form.elements.start_date.value||null,recurrence_mode:mode.value,frequency:form.elements.frequency.value,interval:Number(form.elements.interval.value),weekdays:schedule.weekdays,day_of_month:schedule.day_of_month,month_of_year:schedule.month_of_year,...(!dirty&&schedule.existingDue?{due_date:schedule.existingDue,schedule_anchor:schedule.anchor}:{})},request=++previewRequest;summary.innerHTML=this.editorScheduleHtml(task,[],"Fälligkeiten werden berechnet…");more.hidden=true;try{const result=await this.ws({type:"home_tasker/task/preview_next_due",...task,count:visibleCount});if(request===previewRequest&&summary.isConnected){summary.innerHTML=this.editorScheduleHtml(task,result.due_dates);more.hidden=visibleCount>=24;}}catch(err){if(request===previewRequest&&summary.isConnected)summary.innerHTML=this.editorScheduleHtml(task,[],"Fälligkeiten konnten nicht berechnet werden");}};
    const changed=callback=>{dirty=true;callback();},renderStart=()=>{startTrigger.textContent=startInput.value?this.date(startInput.value):"auswählen";startClear.hidden=!startInput.value;},render=()=>{const fixed=mode.value==="fixed",kind=form.elements.frequency.value;options.hidden=!fixed||kind==="daily";if(!fixed||kind==="daily"){options.innerHTML="";updateSummary();return;}if(kind==="weekly"){options.innerHTML=`<span>Wochentage</span><div class="weekday-buttons" style="display:flex;width:100%;gap:4px;flex-wrap:nowrap">${["Mo","Di","Mi","Do","Fr","Sa","So"].map((d,i)=>`<button type="button" data-day="${i}" class="weekday ${schedule.weekdays.includes(i)?"selected":""}" style="flex:1 1 0;min-width:0;min-height:44px;padding:0">${d}</button>`).join("")}</div>`;options.querySelectorAll("[data-day]").forEach(button=>button.onclick=()=>changed(()=>{const day=Number(button.dataset.day);schedule.weekdays.includes(day)?schedule.weekdays=schedule.weekdays.filter(x=>x!==day):schedule.weekdays.push(day);button.classList.toggle("selected");updateSummary();}));}else if(kind==="yearly"){const months=Array.from({length:12},(_,i)=>`<option value="${i+1}" ${Number(schedule.month_of_year)===i+1?"selected":""}>${new Intl.DateTimeFormat(this.locale(),{month:"long"}).format(new Date(2024,i,1))}</option>`).join("");options.innerHTML=`<div class="annual-row" style="display:flex;gap:10px"><label style="flex:1;min-width:0">Tag<select class="month-day">${days()}</select></label><label style="flex:1;min-width:0">Monat<select class="year-month">${months}</select></label></div>`;options.querySelector(".year-month").onchange=e=>changed(()=>{schedule.month_of_year=Number(e.target.value);updateSummary();});options.querySelector(".month-day").onchange=e=>changed(()=>{schedule.day_of_month=e.target.value==="last"?"last":Number(e.target.value);updateSummary();});}else{options.innerHTML=`<label>Am Tag<select class="month-day">${days()}</select></label>`;options.querySelector(".month-day").onchange=e=>changed(()=>{schedule.day_of_month=e.target.value==="last"?"last":Number(e.target.value);updateSummary();});}updateSummary();};
    more.onclick=()=>{visibleCount+=1;updateSummary();};startTrigger.onclick=()=>{try{if(startInput.showPicker)startInput.showPicker();else startInput.click();}catch{startInput.click();}};startClear.onclick=()=>changed(()=>{startInput.value="";renderStart();updateSummary();});mode.addEventListener("change",()=>changed(render));form.elements.frequency.addEventListener("change",()=>changed(render));form.elements.interval.addEventListener("input",()=>changed(updateSummary));startInput.addEventListener("change",()=>changed(()=>{renderStart();updateSummary();}));renderStart();render();
  }
  dialog(title,fields,onSave,after,onCancel){const root=this.shadowRoot.querySelector(".dialogs");root.innerHTML=`<div class="overlay"><div class="modal">${this.modalHeader(title)}<form>${fields.map(f=>this.field(f)).join("")}<div class="error" style="display:none"></div><div class="actions"><button class="primary">${L.save}</button></div></form></div></div>`;const form=root.querySelector("form"),error=root.querySelector(".error");let saved=false;const close=async()=>{root.innerHTML="";if(!saved&&onCancel)await onCancel();};root.querySelector(".modal-close").onclick=close;root.querySelector(".overlay").onclick=e=>{if(e.target===e.currentTarget)close();};if(after)after(root.querySelector(".modal"));form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(fields.map(f=>[f[0],form.elements[f[0]].value.trim()]));if(fields.some(f=>f[3]&&!v[f[0]])){error.style.display="block";error.textContent="Bitte Pflichtfelder ausfüllen.";return;}try{await onSave(v);saved=true;await close();}catch(err){error.style.display="block";error.textContent=`Fehler: ${err.message||err}`;}};}
  field(f){const [key,label,value,,type="text",opts=[]]=f,caption=`<span>${label}${key==="name"?'<span class="required">*</span>':""}</span>`;if(type==="textarea")return `<label data-field="${key}">${caption}<textarea name="${key}" style="resize:vertical">${esc(value)}</textarea></label>`;if(type==="select")return `<label data-field="${key}">${caption}<select name="${key}">${opts.map(o=>`<option value="${esc(o[0])}" ${value===o[0]?"selected":""}>${esc(o[1])}</option>`).join("")}</select></label>`;return `<label data-field="${key}">${caption}<input name="${key}" type="${type}" value="${esc(value)}" ${type==="number"?'min="1"':""}></label>`;}
  async mountDetails(modal,task,pendingFiles,pendingHistory,newUploads){
    const form=modal.querySelector("form"),actions=form.querySelector(".actions"),filesBox=document.createElement("section"),historyBox=document.createElement("section");
    filesBox.className="details files-box";historyBox.className="details history-box";
    filesBox.innerHTML=`<h3>${L.files}</h3><input type="file" multiple hidden><div class="file-list"></div><button type="button" class="drop-zone" style="width:100%;min-height:72px;margin-top:10px;border:2px dashed var(--divider-color);background:var(--secondary-background-color);color:var(--secondary-text-color);display:flex;align-items:center;justify-content:center;gap:8px"><ha-icon icon="mdi:tray-arrow-up"></ha-icon><span>Dateien hierher ziehen oder antippen</span></button>`;
    historyBox.innerHTML=`<h3>${L.history}</h3><div class="history-list">Laden…</div>`;form.insertBefore(filesBox,actions);form.insertBefore(historyBox,actions);
    const renderFiles=()=>{const files=this.attachments.filter(a=>a.task_id===task.id);filesBox.querySelector(".file-list").innerHTML=files.length?files.map(f=>`<div data-file="${f.id}" class="detail-row ${pendingFiles.has(f.id)?"pending":""}">${this.fileLink(f)}<span class="file-size">${this.size(f.size)}</span><button type="button" class="editor-action remove ${pendingFiles.has(f.id)?"":"danger"}" aria-label="${pendingFiles.has(f.id)?"Entfernen rückgängig machen":"Datei entfernen"}" title="${pendingFiles.has(f.id)?"Rückgängig":"Entfernen"}"><ha-icon icon="mdi:${pendingFiles.has(f.id)?"undo":"delete"}"></ha-icon></button></div>`).join(""):`<small>${L.noFiles}</small>`;filesBox.querySelectorAll("[data-file]").forEach(r=>{const f=files.find(x=>x.id===r.dataset.file);r.querySelector(".remove").onclick=()=>{pendingFiles.has(f.id)?pendingFiles.delete(f.id):pendingFiles.add(f.id);renderFiles();};});};
    renderFiles();const input=filesBox.querySelector('input[type="file"]'),dropZone=filesBox.querySelector(".drop-zone"),remember=file=>newUploads.add(file.id),showUploadError=err=>{const error=form.querySelector(".error");error.style.display="block";error.textContent=`Fehler: ${err.message||err}`;},upload=async files=>{try{await this.upload(task.id,files,remember);}catch(err){showUploadError(err);}finally{renderFiles();}},resetDropZone=()=>{dropZone.style.borderColor="var(--divider-color)";dropZone.style.background="var(--secondary-background-color)";};dropZone.onclick=()=>input.click();input.onchange=async()=>{await upload([...input.files]);input.value="";};["dragover","dragenter"].forEach(x=>dropZone.addEventListener(x,e=>{e.preventDefault();dropZone.style.borderColor="var(--primary-color)";dropZone.style.background="var(--primary-background-color)";}));dropZone.ondragleave=resetDropZone;dropZone.ondrop=async e=>{e.preventDefault();resetDropZone();await upload([...e.dataTransfer.files]);};
    const data=await this.ws({type:"home_tasker/history/list",task_id:task.id}),hist=historyBox.querySelector(".history-list");hist.style.overflowX="auto";hist.innerHTML=data.history.length?data.history.map(h=>this.historyRow(h,true)).join(""):`<small>${L.noHistory}</small>`;hist.querySelectorAll("[data-history]").forEach(r=>r.querySelector(".remove").onclick=()=>{pendingHistory.has(r.dataset.history)?pendingHistory.delete(r.dataset.history):pendingHistory.add(r.dataset.history);r.classList.toggle("pending");const button=r.querySelector(".remove"),pending=pendingHistory.has(r.dataset.history);button.classList.toggle("danger",!pending);button.setAttribute("aria-label",pending?"Entfernen rückgängig machen":"Verlaufseintrag entfernen");button.title=pending?"Rückgängig":"Entfernen";button.innerHTML=`<ha-icon icon="mdi:${pending?"undo":"delete"}"></ha-icon>`;});
  }
  prepareDetails(){this.shadowRoot.querySelectorAll(".modal .details:not([data-collapsible])").forEach(box=>{const title=box.querySelector(":scope>h3");if(!title)return;box.dataset.collapsible="";const toggle=document.createElement("button"),content=document.createElement("div");toggle.type="button";toggle.className="details-toggle";toggle.setAttribute("aria-expanded","false");toggle.innerHTML=`<h3>${title.innerHTML}</h3><ha-icon icon="mdi:chevron-right"></ha-icon>`;content.className="details-content";[...box.children].forEach(child=>{if(child!==title)content.append(child);});title.replaceWith(toggle);box.append(content);toggle.onclick=()=>{const open=box.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open));};});}
  fileLink(file){const name=esc(file.filename),url=this.signedFiles.get(file.id);return url?`<a class="filename" href="${esc(url)}" target="_blank" rel="noopener noreferrer" title="${name}" style="min-width:0;white-space:nowrap;text-overflow:ellipsis;display:block">${name}</a>`:`<span class="filename" title="${name}" style="min-width:0;white-space:nowrap;text-overflow:ellipsis;display:block">${name}</span>`;}
  token(){return this._hass?.auth?.data?.access_token||null;} async upload(taskId,files,onUploaded){for(const file of files){const fd=new FormData();fd.append("task_id",taskId);fd.append("file",file,file.name);const r=await fetch("/api/home_tasker/upload",{method:"POST",headers:this.token()?{authorization:`Bearer ${this.token()}`}:{},body:fd});if(!r.ok)throw new Error(`Upload fehlgeschlagen (${r.status})`);const record=await r.json();this.attachments.push(record);if(onUploaded)onUploaded(record);}await this.signFiles();}
  locale(){return this._hass?.locale?.language||navigator.language||"de-CH";}
  date(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");return m?new Date(+m[1],+m[2]-1,+m[3]).toLocaleDateString(this.locale()):v;}
  dueDateParts(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");if(!m)return {weekday:"",date:String(v||"")};const value=new Date(+m[1],+m[2]-1,+m[3]),locale=this.locale();return {weekday:value.toLocaleDateString(locale,{weekday:"long"}),date:value.toLocaleDateString(locale,{year:"numeric",month:"2-digit",day:"2-digit"})};}
  dueDate(v){const parts=this.dueDateParts(v);return [parts.weekday,parts.date].filter(Boolean).join(" ");}
  relativeDate(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||""),base=/^(\d{4})-(\d{2})-(\d{2})/.exec(this.today||"");if(!m||!base)return v;const target=Date.UTC(+m[1],+m[2]-1,+m[3]),today=Date.UTC(+base[1],+base[2]-1,+base[3]),days=Math.round((target-today)/86400000),absolute=Math.abs(days);let value=days,unit="day";if(absolute>=730){value=Math.round(days/365.2425);unit="year";}else if(absolute>=60){value=Math.round(days/30.4375);unit="month";}else if(absolute>=14){value=Math.round(days/7);unit="week";}return new Intl.RelativeTimeFormat("de",{numeric:"auto"}).format(value,unit);}
  size(n){return n<1024?`${n} B`:n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;}
}
if(!customElements.get("home-tasker-panel"))customElements.define("home-tasker-panel",HomeTaskerPanel);
