import { L, esc, markdown } from "./shared.js";

export const withTaskViewer = Base => class extends Base {
  async taskViewer(task){
    const root=this.shadowRoot.querySelector(".dialogs"),group=this.groups.find(item=>item.id===task.group_id),assignee=this.users.find(user=>user.id===task.assignee_user_id),files=this.attachments.filter(file=>file.task_id===task.id);
    root.innerHTML=`<div class="overlay viewer-overlay"><div class="modal task-viewer" role="dialog" aria-modal="true" aria-labelledby="task-viewer-title"><style>.task-viewer{display:flex;flex-direction:column;gap:16px}.viewer-pills{display:flex;gap:8px;flex-wrap:wrap}.viewer-pills .pill{display:inline-flex;align-items:center;gap:5px}.viewer-section h3{margin:0 0 8px;font-size:13px;color:var(--secondary-text-color)}.viewer-section p{margin:0}.viewer-description{line-height:1.55;overflow-wrap:anywhere}.viewer-description>:first-child{margin-top:0}.viewer-description>:last-child{margin-bottom:0}.viewer-description h1,.viewer-description h2,.viewer-description h3{color:var(--primary-text-color);font-size:1.2em;margin:16px 0 6px}.viewer-description blockquote{margin:10px 0;padding-left:12px;border-left:3px solid var(--primary-color);color:var(--secondary-text-color)}.viewer-description pre,.viewer-description code{background:var(--secondary-background-color);border-radius:5px}.viewer-description code{padding:2px 4px}.viewer-description pre{padding:10px;overflow:auto}.viewer-description pre code{padding:0}.viewer-description a{color:var(--primary-color)}.viewer-file-list .file-size{flex:0;white-space:nowrap;margin-left:auto}.viewer-history-list{overflow-x:auto}.viewer-actions{display:flex;justify-content:flex-end}.viewer-notes textarea{min-height:72px;resize:vertical}.viewer-complete{display:flex;align-items:center;gap:7px;background:var(--success-color,#43a047);color:#fff;padding:9px 13px}</style><div class="modal-header"><button type="button" class="modal-close" aria-label="Schließen" title="Schließen"><ha-icon icon="mdi:close"></ha-icon></button><h2 id="task-viewer-title">${esc(task.name)}</h2></div><div class="viewer-pills"><span class="pill"><ha-icon icon="mdi:devices"></ha-icon>${esc(group?.name||"Keine Gruppe")}</span><span class="pill"><ha-icon icon="mdi:account"></ha-icon>${esc(assignee?.name||"Nicht zugewiesen")}</span></div><section class="viewer-section"><h3>Beschreibung</h3><div class="viewer-description">${task.description?markdown(task.description):"<p>Keine Beschreibung</p>"}</div></section><section class="viewer-section"><h3>Planung</h3><p>${esc(this.scheduleText(task))}</p></section><section class="details viewer-box"><h3>${L.files}</h3><div class="viewer-file-list">${files.length?files.map(file=>`<div class="detail-row">${this.fileLink(file)}<span class="file-size">${this.size(file.size)}</span></div>`).join(""):`<small>${L.noFiles}</small>`}</div></section><section class="details viewer-box"><h3>${L.history}</h3><div class="viewer-history-list">Laden…</div></section><label class="viewer-notes"><span>Notizen zur Erledigung</span><textarea placeholder="Optionale Notizen für den Verlauf"></textarea></label><div class="viewer-actions"><button type="button" class="viewer-complete"><ha-icon icon="mdi:check-circle-outline"></ha-icon><span>Erledigt</span></button></div></div></div>`;
    root.insertAdjacentHTML("beforeend",this.themeStyles()+this.buttonThemeStyles()+this.compactDetailsStyles()+this.iconHoverStyles());root.querySelectorAll(".viewer-section p").forEach(text=>text.style.whiteSpace="pre-line");let closed=false;const close=()=>{if(closed)return;closed=true;window.removeEventListener("keydown",onKey);root.innerHTML="";},onKey=e=>{if(e.key==="Escape")close();};window.addEventListener("keydown",onKey);root.querySelector(".modal-close").onclick=close;root.querySelector(".viewer-overlay").onclick=e=>{if(e.target===e.currentTarget)close();};root.querySelector(".viewer-complete").onclick=async()=>{const notes=root.querySelector(".viewer-notes textarea").value.trim()||null;if(!await this.confirmAction("Task erledigen",`Möchtest du den Task „${task.name}“ als erledigt markieren?`,"Erledigen","success","mdi:check-circle-outline"))return;await this.ws({type:"home_tasker/task/complete",task_id:task.id,notes});close();await this.load();};
    try{const data=await this.ws({type:"home_tasker/history/list",task_id:task.id});if(closed)return;const history=root.querySelector(".viewer-history-list");history.innerHTML=data.history.length?data.history.map(entry=>this.historyRow(entry)).join(""):`<small>${L.noHistory}</small>`;}catch(err){if(!closed)root.querySelector(".viewer-history-list").innerHTML=`<small>Verlauf konnte nicht geladen werden: ${esc(err.message||err)}</small>`;}
  }
};
