import { L, esc } from "./shared.js";

export const TASK_ROW_HOVER_BACKGROUND = "var(--ha-color-fill-neutral-quiet-resting,var(--primary-background-color))";

export function sortTasksByDue(tasks, locale="de") {
  return [...tasks].sort((a,b)=>(a.due_date||"").localeCompare(b.due_date||"")||(a.name||"").localeCompare(b.name||"",locale));
}

export const withTaskList = Base => class extends Base {
  tasksOf(id){ return this.tasks.filter(t=>t.group_id===id); }
  sortedTasks(tasks){if(this.sort==="due")return sortTasksByDue(tasks);return [...tasks].sort((a,b)=>a.name.localeCompare(b.name,"de"));}
  due(t){return Boolean(this.today&&t.due_date<=this.today);}
  sorted(){ const g=[...this.groups]; if(this.sort==="due"){const first=x=>this.tasksOf(x.id).reduce((date,t)=>t.due_date<date?t.due_date:date,"9999-12-31");g.sort((a,b)=>first(a).localeCompare(first(b))||a.name.localeCompare(b.name,"de"));}else g.sort((a,b)=>a.name.localeCompare(b.name,"de")); return g; }
  render(){
    if(!this.shadowRoot.querySelector(".app")) this.shadowRoot.innerHTML=`${this.styles()}<style>.section-title{display:flex;align-items:center}.section-title h3{margin:0}.section-title .browse{float:none;margin-left:auto}.file-list .file-size{flex:0;white-space:nowrap;margin-left:auto}.weekday-buttons{display:flex;gap:5px;flex-wrap:wrap}.weekday{border:1px solid var(--divider-color);background:transparent}.weekday.selected{border-color:var(--primary-color);background:var(--primary-color);color:white}.schedule-options{color:var(--secondary-text-color);font-size:13px}.schedule-options>span{display:block;margin-bottom:5px}.group-head:hover,.add:hover{background:var(--secondary-background-color)}.task:hover{background:${TASK_ROW_HOVER_BACKGROUND}}.task{cursor:grab;user-select:none}.task.dragging{opacity:.45}.group-head.drop-target{outline:2px solid var(--primary-color);outline-offset:-2px;background:var(--secondary-background-color)}.add{min-height:44px;box-sizing:border-box;display:flex;align-items:center;justify-content:center}.open-count{background:var(--error-color,#d32f2f);color:#fff}.group-actions{display:flex;justify-content:flex-end;gap:8px;padding:6px 8px 8px}.group-actions button,.editor-action{font-weight:inherit}.group-actions .edit-group,.editor-action.task-complete{background:var(--primary-color);color:var(--text-primary-color,#fff)}.group-actions .delete-group,.editor-action.danger{color:var(--error-color,#d32f2f)}.actions i{flex:1}.modal h2{position:sticky;top:-20px;z-index:2;margin:-20px -20px 4px;padding:20px;background:var(--card-background-color,#fff);border-bottom:1px solid var(--divider-color)}.details-toggle{display:flex;align-items:center;width:100%;padding:0;background:transparent;color:var(--secondary-text-color);text-align:left}.details-toggle h3{margin:0;flex:1}.details-toggle ha-icon{transition:transform .2s}.details.open>.details-toggle ha-icon{transform:rotate(90deg)}.details-content{display:none;flex-direction:column;gap:10px;margin-top:10px}.details.open>.details-content{display:flex}</style><div class="app"></div><div class="dialogs"></div>`;
    const app=this.shadowRoot.querySelector(".app");
    app.innerHTML=`<style>main{padding-bottom:96px}.task{cursor:pointer;user-select:auto}.floating-add{position:fixed;right:16px;bottom:calc(16px + env(safe-area-inset-bottom));z-index:5;padding:11px 16px;background:var(--primary-color);color:#fff;border-radius:12px;box-shadow:var(--ha-card-box-shadow,0 3px 8px #0004);font:inherit}.required{color:var(--error-color,#d32f2f);margin-left:3px}.version{right:10px;left:auto;top:8px;bottom:auto}.modal-header{position:sticky;top:-20px;z-index:3;margin:-20px -20px 4px;padding:10px 12px;background:var(--card-background-color,#fff);border-bottom:1px solid var(--divider-color);display:flex;align-items:center;gap:8px}.modal-header h2{position:static;margin:0;padding:0;border:0;flex:1}.modal-close{display:flex;align-items:center;justify-content:center;width:40px;height:40px;padding:0;background:transparent;color:var(--primary-text-color);border-radius:50%}</style><main><header><div><h1>Home Tasker</h1><p>Wiederkehrende Aufgaben im Blick behalten</p></div></header>
      <nav><i></i><button class="link expand">${this.groups.every(g=>this.expanded.has(g.id))?"Alle zuklappen":"Alle aufklappen"}</button><select class="sort"><option value="name">Name</option><option value="due">Fälligkeit</option></select></nav>
      <section>${this.sorted().map(g=>this.groupRow(g)).join("")}</section><button class="floating-add">${L.addTask}</button><small class="version">v${this.constructor.version}</small></main>`;
    app.insertAdjacentHTML("beforeend",this.themeStyles()+this.buttonThemeStyles()+this.compactDetailsStyles()+this.iconHoverStyles()+this.groupListStyles());
    app.querySelector(".sort").value=this.sort;
    app.querySelector(".expand").onclick=()=>{ const all=this.groups.every(g=>this.expanded.has(g.id)); this.expanded=all?new Set():new Set(this.groups.map(g=>g.id)); this.render(); };
    app.querySelector(".sort").onchange=e=>{this.sort=e.target.value;this.render();};
    app.querySelector(".floating-add").onclick=()=>this.taskEditor(null);
    app.querySelectorAll(".group").forEach(el=>this.wireGroup(el));
  }
  groupRow(g){ const shown=this.sortedTasks(this.tasksOf(g.id)), open=this.expanded.has(g.id), due=shown.filter(t=>this.due(t)).length;
    return `<article class="group" data-group="${g.id}"><div class="group-head" role="button" tabindex="0"><ha-icon class="chevron" icon="mdi:chevron-${open?"down":"right"}"></ha-icon><strong>${esc(g.name)}</strong>${due?`<span class="pill open-count">${due}</span>`:""}<i></i><button class="edit-group icon" aria-label="Gruppe bearbeiten" title="Gruppe bearbeiten"><ha-icon icon="mdi:pencil"></ha-icon></button></div>${open?`<div class="tasks">${shown.map(t=>this.taskRow(t)).join("")}</div>`:""}</article>`; }
  fileNameParts(filename){const name=String(filename||""),dot=name.lastIndexOf(".");return dot>0&&dot<name.length-1?{base:name.slice(0,dot),extension:name.slice(dot)}:{base:name,extension:""};}
  filePill(file){const name=String(file.filename||""),parts=this.fileNameParts(name),url=this.signedFiles.get(file.id),content=`<span style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(parts.base)}</span><span style="flex:none;white-space:nowrap">${esc(parts.extension)}</span>`,style="display:inline-flex;align-items:center;max-width:160px;min-width:0;color:var(--primary-color);text-decoration:none";return url?`<a class="pill file-pill" href="${esc(url)}" target="_blank" rel="noopener noreferrer" title="${esc(name)}" style="${style}">${content}</a>`:`<span class="pill file-pill" title="${esc(name)}" style="${style}">${content}</span>`;}
  taskRow(t){ const files=this.attachments.filter(a=>a.task_id===t.id),assignee=this.users.find(user=>user.id===t.assignee_user_id),filePills=files.map(file=>this.filePill(file)).join("");return `<div class="task" data-task="${t.id}" tabindex="0" style="display:grid;grid-template-columns:minmax(0,1fr) 44px;align-items:center;gap:4px;padding:5px 6px 7px 10px"><div class="task-body" style="display:block;min-width:0"><strong>${esc(t.name)}</strong><div class="pills" style="display:flex;gap:6px;flex-wrap:wrap;align-items:center"><span class="pill due-date ${this.due(t)?"due":"ok"}" title="${esc(this.date(t.due_date))}">${esc(this.relativeDate(t.due_date))}</span>${assignee?`<span class="pill">${esc(assignee.name)}</span>`:""}</div>${filePills?`<div class="pills" style="display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin-top:6px">${filePills}</div>`:""}</div><button type="button" class="edit-task-row icon" aria-label="Task bearbeiten" title="Task bearbeiten" style="display:flex;align-items:center;justify-content:center;width:44px;height:44px;padding:0;color:var(--primary-color,#03a9f4)"><ha-icon icon="mdi:pencil"></ha-icon></button></div>`; }
  wireGroup(el){ const g=this.groups.find(x=>x.id===el.dataset.group),head=el.querySelector(".group-head"),toggle=()=>{this.expanded.has(g.id)?this.expanded.delete(g.id):this.expanded.add(g.id);this.render();};head.onclick=toggle;head.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")toggle();};const edit=el.querySelector(".edit-group");edit.onclick=e=>{e.stopPropagation();this.groupEditor(g);};el.querySelectorAll("[data-task]").forEach(row=>{const t=this.tasks.find(x=>x.id===row.dataset.task),editTask=row.querySelector(".edit-task-row");row.onclick=()=>this.taskViewer(t);row.onkeydown=e=>{if(e.target===row&&(e.key==="Enter"||e.key===" "))this.taskViewer(t);};row.querySelectorAll(".file-pill").forEach(file=>file.onclick=e=>e.stopPropagation());editTask.onclick=e=>{e.stopPropagation();this.taskEditor(g.id,t);};}); }
};
