import { L, esc } from "./shared.js";
import { t as tr } from "./localize.js";
import { EDITOR_FILE_GRID, taskFilesBoxHtml, taskHistoryBoxHtml } from "./task-detail-boxes.js";

export { EDITOR_FILE_GRID } from "./task-detail-boxes.js";

function expansionPanel(className,title,expanded=false){const panel=document.createElement("ha-expansion-panel"),header=document.createElement("span"),content=document.createElement("div");panel.className=className;panel.outlined=true;panel.expanded=expanded;header.slot="header";header.textContent=title;content.className="details-content";panel.append(header,content);return {panel,content};}

export const withTaskEditor = Base => class extends Base {
  async taskEditor(task=null){const t=task||{},tagOptions=[...this.tags].sort((a,b)=>(a.name||a.id).localeCompare(b.name||b.id,this.locale())).map(tag=>[tag.id,tag.name||tag.id]);if(t.nfc_tag_id&&!tagOptions.some(([id])=>id===t.nfc_tag_id))tagOptions.push([t.nfc_tag_id,t.nfc_tag_id]);const pendingFiles=new Set(),pendingHistory=new Set(),newUploads=new Set(),today=this.today,dueValue=t.task_due||today,[year,month,day]=dueValue.slice(0,10).split("-").map(Number),due=new Date(Date.UTC(year,month-1,day)),schedule={schedule_weekdays:[...(t.schedule_weekdays?.length?t.schedule_weekdays:[due.getUTCDay()===0?6:due.getUTCDay()-1])],schedule_day:t.schedule_day||day,schedule_month:t.schedule_month||month,existingDue:t.task_due||null,anchor:t.schedule_anchor_date||t.task_due?.slice(0,10)||null};this.dialog(tr(task?"task.edit":"task.new"),[
    ["assignee_id",tr("task.user"),t.assignee_id||"",false,"select",[["",tr("task.unassigned")],...this.users.map(user=>[user.id,user.name])]],["nfc_tag_id",tr("task.nfc_tag_id"),t.nfc_tag_id||"",false,"select",[["",tr("task.no_nfc_tag")],...tagOptions]], ["task_name",tr("task.name"),t.task_name,true],["task_description",tr("task.optional_description"),t.task_description,false,"textarea"],["schedule_start_date",tr("task.schedule_start_date"),t.schedule_start_date||"",false,"date"],["schedule_type",tr("task.recurrence_calculation"),t.schedule_type||"sliding",true,"select",[["fixed",L.fixed],["sliding",L.sliding]]],["schedule_unit",tr("task.schedule_unit"),t.schedule_unit||"monthly",true,"select",[["daily",L.daily],["weekly",L.weekly],["monthly",L.monthly],["yearly",L.yearly]]],["schedule_interval",tr("task.schedule_interval"),t.schedule_interval||1,true,"number"]
  ],async v=>{for(const id of [...pendingHistory]){await this.ws({type:"home_tasker/history/delete",task_id:task.task_id,history_entry_id:id});pendingHistory.delete(id);}for(const id of [...pendingFiles]){await this.ws({type:"home_tasker/attachment/delete",attachment_id:id});pendingFiles.delete(id);}await this.ws({type:`home_tasker/task/${task?"update":"create"}`,...(task?{task_id:task.task_id}:{}),task_name:v.task_name,task_description:v.task_description||null,assignee_id:v.assignee_id||null,nfc_tag_id:v.nfc_tag_id.trim()||null,schedule_start_date:v.schedule_start_date||null,schedule_type:v.schedule_type,schedule_unit:v.schedule_unit,schedule_interval:Number(v.schedule_interval),schedule_weekdays:schedule.schedule_weekdays,schedule_day:schedule.schedule_day,schedule_month:schedule.schedule_month});newUploads.clear();},modal=>{this.arrangeBasics(modal);this.arrangeSchedule(modal,schedule);this.arrangeAssignment(modal);if(task)this.mountDetails(modal,task,pendingFiles,pendingHistory,newUploads);},async()=>{for(const id of newUploads){try{await this.ws({type:"home_tasker/attachment/delete",attachment_id:id});}catch{}}});}
  mountIntervalStepper(field){const input=field.querySelector('input[name="schedule_interval"]'),control=document.createElement("div"),minus=document.createElement("button"),plus=document.createElement("button"),style=document.createElement("style"),schedule_unit=field.parentElement?.querySelector('[data-field="schedule_unit"] select');control.className="schedule_interval-stepper";for(const [button,label,icon] of [[minus,tr("task.interval_decrease"),"minus"],[plus,tr("task.interval_increase"),"plus"]]){button.type="button";button.className="schedule_interval-step";button.setAttribute("aria-label",label);button.innerHTML=`<ha-icon icon="mdi:${icon}"></ha-icon>`;}input.type="text";input.inputMode="numeric";input.pattern="[0-9]*";input.setAttribute("aria-label",tr("task.interval_label"));input.before(control);control.append(minus,input,plus);if(schedule_unit)schedule_unit.classList.add("schedule-select");style.textContent=".schedule-select,.schedule_interval-stepper{box-sizing:border-box;width:100%;height:44px}.schedule_interval-stepper{display:grid;grid-template-columns:42px minmax(36px,1fr) 42px;align-items:center;border:1px solid var(--divider-color);border-radius:8px;background:var(--primary-background-color);overflow:hidden}.schedule_interval-stepper:focus-within{border-color:var(--primary-color)}.schedule_interval-stepper input{box-sizing:border-box;width:100%;height:42px;min-width:0;padding:0 4px;border:0;border-radius:0;background:transparent;font:inherit;text-align:center;outline:0}.schedule_interval-step{display:flex!important;align-items:center;justify-content:center;width:42px!important;min-width:42px!important;height:42px!important;min-height:0!important;padding:0!important;border:0;border-radius:0;background:transparent;color:var(--secondary-text-color)}.schedule_interval-step:hover,.schedule_interval-step:focus-visible{background:var(--ha-color-fill-neutral-quiet-hover,var(--secondary-background-color));color:var(--primary-text-color);outline:0}.schedule_interval-step:disabled{color:var(--disabled-text-color);cursor:default;background:transparent}";field.append(style);const value=()=>Math.max(1,Math.trunc(Number(input.value)||1)),commit=next=>{input.value=String(Math.max(1,next));minus.disabled=value()<=1;input.dispatchEvent(new Event("input",{bubbles:true}));};minus.onclick=()=>commit(value()-1);plus.onclick=()=>commit(value()+1);input.oninput=()=>{input.value=input.value.replace(/\D/g,"");minus.disabled=value()<=1;};input.onblur=()=>commit(value());input.onkeydown=event=>{if(event.key==="ArrowUp"){event.preventDefault();commit(value()+1);}else if(event.key==="ArrowDown"){event.preventDefault();commit(value()-1);}};minus.disabled=value()<=1;}
  arrangeBasics(modal){const form=modal.querySelector("form"),name=form.querySelector('[data-field="task_name"]'),description=form.querySelector('[data-field="task_description"]');for(const [field,placeholder] of [[name,tr("task.name")],[description,tr("task.optional_description")]]){const control=field.querySelector("input,textarea");control.placeholder=placeholder;control.setAttribute("aria-label",placeholder);field.querySelector(":scope > span")?.remove();}form.prepend(name,description);}
  arrangeAssignment(modal){const form=modal.querySelector("form"),fields=[form.querySelector('[data-field="assignee_id"]'),form.querySelector('[data-field="nfc_tag_id"]')],schedule=form.querySelector(".schedule-box"),{panel,content}=expansionPanel("assignment-box",tr("task.assignment"));schedule?schedule.after(panel):form.insertBefore(panel,fields[0]);fields.forEach(field=>content.append(field));}
  arrangeSchedule(modal,schedule){
    const form=modal.querySelector("form"),start=form.querySelector('[data-field="schedule_start_date"]'),startInput=form.elements.schedule_start_date,recurrence=form.querySelector('[data-field="schedule_type"]'),schedule_unit=form.querySelector('[data-field="schedule_unit"]'),schedule_interval=form.querySelector('[data-field="schedule_interval"]'),mode=form.elements.schedule_type,row=document.createElement("div"),options=document.createElement("div"),preview=document.createElement("div"),summary=document.createElement("div"),more=document.createElement("button"),startBox=document.createElement("section"),startTrigger=document.createElement("label"),startText=document.createElement("span"),{panel:box,content}=expansionPanel("schedule-box",tr("task.planning"));
    row.className="schedule_interval-row";options.className="schedule-options ht-label-normal";preview.className="due-preview-list";summary.className="schedule-summary ht-content";form.insertBefore(box,start);row.append(schedule_unit,schedule_interval);content.append(recurrence,row,options);
    this.mountIntervalStepper(schedule_interval);more.type="button";more.className="link show-more-dates ht-label-normal";more.textContent=tr("task.show_more");more.style.cssText="padding:0;min-height:32px";preview.innerHTML=`<h3 class="ht-label-normal" style="margin:0">${tr("task.preview_task_dues")}</h3>`;preview.append(summary,more);
    startBox.className="start-date-option";startBox.style.cssText="display:flex;flex-direction:column;gap:0;margin:0;padding:0";startBox.innerHTML=`<h3 class="start-date-title ht-label-normal" style="margin:0">${tr("task.optional_start_date")}</h3><div class="start-date-actions"></div>`;
    start.remove();startTrigger.className="link start-date-trigger ht-label-normal";startTrigger.style.cssText="position:relative;display:inline-flex;align-items:baseline;padding:0;text-align:left;overflow:hidden;line-height:var(--ha-line-height-normal,1.4)";startInput.style.cssText="position:absolute;inset:0;width:100%;height:100%;margin:0;opacity:0;cursor:pointer";startTrigger.append(startText,startInput);
    startBox.querySelector(".start-date-actions").append(startTrigger);content.append(startBox,preview);
    const days=()=>`${Array.from({length:31},(_,i)=>`<option value="${i+1}" ${String(schedule.schedule_day)===String(i+1)?"selected":""}>${i+1}</option>`).join("")}<option value="last" ${schedule.schedule_day==="last"?"selected":""}>${tr("task.last_day")}</option>`;
    let previewRequest=0,dirty=false,visibleCount=4;const updateSummary=async()=>{const task={schedule_start_date:form.elements.schedule_start_date.value||null,schedule_type:mode.value,schedule_unit:form.elements.schedule_unit.value,schedule_interval:Number(form.elements.schedule_interval.value),schedule_weekdays:schedule.schedule_weekdays,schedule_day:schedule.schedule_day,schedule_month:schedule.schedule_month,...(!dirty&&schedule.existingDue?{task_due:schedule.existingDue,schedule_anchor_date:schedule.anchor}:{})},request=++previewRequest;if(!summary.dataset.ready){summary.innerHTML=this.editorScheduleHtml(task,[],tr("task.calculating_task_dues"));more.hidden=true;}summary.setAttribute("aria-busy","true");try{const result=await this.ws({type:"home_tasker/task/preview_next_due",...task,count:visibleCount});if(request===previewRequest&&summary.isConnected){summary.innerHTML=this.editorScheduleHtml(task,result.task_dues);summary.dataset.ready="true";summary.setAttribute("aria-busy","false");more.hidden=visibleCount>=24;}}catch(err){if(request===previewRequest&&summary.isConnected){summary.innerHTML=this.editorScheduleHtml(task,[],tr("task.task_dues_failed"));summary.setAttribute("aria-busy","false");}}};
    const changed=callback=>{dirty=true;callback();},renderStart=()=>{startText.textContent=startInput.value?this.date(startInput.value):tr("task.select");},render=()=>{const fixed=mode.value==="fixed",kind=form.elements.schedule_unit.value;options.hidden=!fixed||kind==="daily";if(!fixed||kind==="daily"){options.innerHTML="";updateSummary();return;}if(kind==="weekly"){options.innerHTML=`<span>${tr("task.schedule_weekdays")}</span><div class="weekday-buttons" style="display:flex;width:100%;gap:4px;flex-wrap:nowrap">${Array.from({length:7},(_,i)=>new Intl.DateTimeFormat(this.locale(),{weekday:"short",timeZone:"UTC"}).format(new Date(Date.UTC(2024,0,i+1)))).map((d,i)=>`<button type="button" data-day="${i}" class="weekday ${schedule.schedule_weekdays.includes(i)?"selected":""}" style="flex:1 1 0;min-width:0;min-height:44px;padding:0">${d}</button>`).join("")}</div>`;options.querySelectorAll("[data-day]").forEach(button=>button.onclick=()=>changed(()=>{const day=Number(button.dataset.day);schedule.schedule_weekdays.includes(day)?schedule.schedule_weekdays=schedule.schedule_weekdays.filter(x=>x!==day):schedule.schedule_weekdays.push(day);button.classList.toggle("selected");updateSummary();}));}else if(kind==="yearly"){const months=Array.from({length:12},(_,i)=>`<option value="${i+1}" ${Number(schedule.schedule_month)===i+1?"selected":""}>${new Intl.DateTimeFormat(this.locale(),{month:"long"}).format(new Date(2024,i,1))}</option>`).join("");options.innerHTML=`<div class="annual-row" style="display:flex;gap:10px"><label style="flex:1;min-width:0">${tr("task.day")}<select class="month-day ht-content">${days()}</select></label><label style="flex:1;min-width:0">${tr("task.month")}<select class="year-month ht-content">${months}</select></label></div>`;options.querySelector(".year-month").onchange=e=>changed(()=>{schedule.schedule_month=Number(e.target.value);updateSummary();});options.querySelector(".month-day").onchange=e=>changed(()=>{schedule.schedule_day=e.target.value==="last"?"last":Number(e.target.value);updateSummary();});}else{options.innerHTML=`<label>${tr("task.on_day")}<select class="month-day ht-content">${days()}</select></label>`;options.querySelector(".month-day").onchange=e=>changed(()=>{schedule.schedule_day=e.target.value==="last"?"last":Number(e.target.value);updateSummary();});}updateSummary();};
    more.onclick=()=>{visibleCount+=1;updateSummary();};mode.addEventListener("change",()=>changed(render));form.elements.schedule_unit.addEventListener("change",()=>changed(render));form.elements.schedule_interval.addEventListener("input",()=>changed(updateSummary));startInput.addEventListener("click",()=>{try{startInput.showPicker?.();}catch{}});startInput.addEventListener("change",()=>changed(()=>{renderStart();updateSummary();}));renderStart();render();
  }
  async mountDetails(modal,task,pendingFiles,pendingHistory,newUploads){
    const form=modal.querySelector("form"),formEnd=form.querySelector(".form-end");formEnd.insertAdjacentHTML("beforebegin",taskFilesBoxHtml(this,task,{editable:true,pending:pendingFiles})+taskHistoryBoxHtml(this,null,{editable:true}));const filesBox=form.querySelector(".files-box"),historyBox=form.querySelector(".history-box");
    const renderFiles=()=>{const replacement=document.createElement("div");replacement.innerHTML=taskFilesBoxHtml(this,task,{editable:true,pending:pendingFiles});filesBox.querySelector(".file-list").replaceWith(replacement.firstElementChild.querySelector(".file-list"));const files=this.attachments.filter(a=>a.task_id===task.task_id);filesBox.querySelectorAll("[data-file]").forEach(r=>{const f=files.find(x=>x.attachment_id===r.dataset.file);r.querySelector(".remove").onclick=()=>{pendingFiles.has(f.attachment_id)?pendingFiles.delete(f.attachment_id):pendingFiles.add(f.attachment_id);renderFiles();};});this.wireFileOpeners(filesBox,this._activeFormDialog||this);};
    renderFiles();const input=filesBox.querySelector('input[type="file"]'),dropZone=filesBox.querySelector(".attachment-drop-zone"),choose=filesBox.querySelector(".choose-files"),remember=file=>newUploads.add(file.attachment_id),showUploadError=err=>{const error=form.querySelector(".error");error.style.display="block";error.textContent=tr("common.error",{message:err.message||err});},upload=async files=>{if(!files.length)return;try{await this.upload(task.task_id,files,remember);}catch(err){showUploadError(err);}finally{renderFiles();}};choose.onclick=()=>input.click();input.onchange=async()=>{await upload([...input.files]);input.value="";};["dragenter","dragover"].forEach(type=>dropZone.addEventListener(type,event=>{event.preventDefault();dropZone.dataset.dragging="";}));["dragleave","dragend"].forEach(type=>dropZone.addEventListener(type,()=>delete dropZone.dataset.dragging));dropZone.ondrop=async event=>{event.preventDefault();delete dropZone.dataset.dragging;await upload([...event.dataTransfer.files]);};
    const data=await this.ws({type:"home_tasker/history/list",task_id:task.task_id}),hist=historyBox.querySelector(".history-list");hist.style.overflowX="auto";hist.innerHTML=data.history.length?data.history.map(h=>this.historyRow(h,true)).join(""):`<small class="ht-content">${L.noHistory}</small>`;hist.querySelectorAll("[data-history]").forEach(r=>r.querySelector(".remove").onclick=()=>{pendingHistory.has(r.dataset.history)?pendingHistory.delete(r.dataset.history):pendingHistory.add(r.dataset.history);r.classList.toggle("pending");const button=r.querySelector(".remove"),pending=pendingHistory.has(r.dataset.history);button.classList.toggle("danger",!pending);button.setAttribute("aria-label",pending?tr("history.undo_remove"):tr("history.remove"));button.title=pending?tr("common.undo"):tr("common.remove");button.innerHTML=`<ha-icon icon="mdi:${pending?"undo":"delete"}"></ha-icon>`;});
  }
};
