import { L, esc } from "./shared.js";
import { ROW_ACTION_MENU_STYLES, rowActionButtonHtml } from "./action-menu.js";
import { t } from "./localize.js";

export const TASK_ROW_BACKGROUND = "transparent";
export const TASK_ROW_HOVER_BACKGROUND = "rgba(var(--rgb-primary-text-color),0.04)";
export const LIST_SECONDARY_ACTION_COLOR = "var(--secondary-text-color)";

export function sortTasksByDue(tasks, locale="en") {
  return [...tasks].sort((a,b)=>(a.due_date||"").localeCompare(b.due_date||"")||(a.name||"").localeCompare(b.name||"",locale));
}

export const withTaskList = Base => class extends Base {
  tagName(task){const id=task?.nfc_tag_id;return id?(this.tags?.find(tag=>tag.id===id)?.name||id):"";}
  tasksOf(id){ return this.tasks.filter(t=>t.group_id===id); }
  sortedTasks(tasks){if(this.sort==="due")return sortTasksByDue(tasks,this.locale());return [...tasks].sort((a,b)=>a.name.localeCompare(b.name,this.locale()));}
  due(t){return Boolean(this.today&&t.due_date<=this.today);}
  sorted(){ const g=[...this.groups]; if(this.sort==="due"){const first=x=>this.tasksOf(x.id).reduce((date,t)=>t.due_date<date?t.due_date:date,"9999-12-31");g.sort((a,b)=>first(a).localeCompare(first(b))||a.name.localeCompare(b.name,this.locale()));}else g.sort((a,b)=>a.name.localeCompare(b.name,this.locale())); return g; }
  render(){
    this.closeActionMenu();
    if(!this.shadowRoot.querySelector(".app")) this.shadowRoot.innerHTML=`${this.styles()}<style>.task:hover{background:${TASK_ROW_HOVER_BACKGROUND}}.task{background:${TASK_ROW_BACKGROUND};cursor:grab;user-select:none}.task.dragging{opacity:.45}.group-head.drop-target{outline:2px solid var(--primary-color);outline-offset:-2px;background:var(--secondary-background-color)}</style><div class="app"></div>`;
    const app=this.shadowRoot.querySelector(".app");
    app.innerHTML=`<style>main{padding-bottom:36px}.task{cursor:pointer;user-select:auto}.sort{box-sizing:border-box;min-height:44px;padding:9px;border:1px solid var(--divider-color);border-radius:8px;background:var(--primary-background-color);color:var(--primary-text-color);font:inherit}.placeholder-add{display:flex;align-items:center;justify-content:flex-start;gap:7px;width:100%;min-height:52px;padding:4px 12px;border:1px dashed var(--divider-color);border-radius:10px;background:transparent;color:var(--secondary-text-color);font:inherit;text-align:left}.placeholder-add:hover,.placeholder-add:focus-visible{background:${TASK_ROW_HOVER_BACKGROUND};border-color:var(--secondary-text-color);outline:0}.list-add{margin-bottom:8px}.group-add{width:calc(100% - 20px);margin:8px 10px}.version{right:10px;left:auto;top:8px;bottom:auto}</style><main><header><div><h1>Home Tasker</h1><p>${t("panel.subtitle")}</p></div></header>
      <nav><i></i><button class="link expand" style="color:${LIST_SECONDARY_ACTION_COLOR}">${t(this.groups.every(g=>this.expanded.has(g.id))?"panel.collapse_all":"panel.expand_all")}</button><select class="sort" aria-label="${t("panel.sort")}"><option value="name">${t("panel.sort_name")}</option><option value="due">${t("panel.sort_due")}</option></select></nav>
      <button class="placeholder-add list-add"><ha-icon icon="mdi:plus"></ha-icon><span>${L.addTask}</span></button><section>${this.sorted().map(g=>this.groupRow(g)).join("")}</section><small class="version">v${this.constructor.version}</small></main>`;
    app.insertAdjacentHTML("beforeend",'<style>.placeholder-add{justify-content:center;text-align:center}</style>'+ROW_ACTION_MENU_STYLES+this.themeStyles()+this.typographyStyles()+this.buttonThemeStyles()+this.iconHoverStyles()+this.groupListStyles());
    app.querySelector(".sort").value=this.sort;
    app.querySelector(".expand").onclick=()=>{ const all=this.groups.every(g=>this.expanded.has(g.id)); this.expanded=all?new Set():new Set(this.groups.map(g=>g.id)); this.render(); };
    app.querySelector(".sort").onchange=e=>{this.sort=e.target.value;this.render();};
    app.querySelector(".list-add").onclick=()=>this.taskEditor(null);
    app.querySelectorAll(".group").forEach(el=>this.wireGroup(el));
  }
  groupRow(g){ const shown=this.sortedTasks(this.tasksOf(g.id)), open=this.expanded.has(g.id), due=shown.filter(t=>this.due(t)).length;
    return `<article class="group" data-group="${g.id}"><div class="group-head" role="button" tabindex="0"><ha-icon class="chevron" icon="mdi:chevron-${open?"down":"right"}"></ha-icon><strong>${esc(g.name)}</strong>${due?`<span class="pill open-count">${due}</span>`:""}<i></i>${rowActionButtonHtml("group",g.id)}</div>${open?`<div class="tasks">${shown.map(t=>this.taskRow(t)).join("")}<button class="placeholder-add group-add"><ha-icon icon="mdi:plus"></ha-icon><span>${L.addTask}</span></button></div>`:""}</article>`; }
  fileNameParts(filename){const name=String(filename||""),dot=name.lastIndexOf(".");return dot>0&&dot<name.length-1?{base:name.slice(0,dot),extension:name.slice(dot)}:{base:name,extension:""};}
  filePill(file){const name=String(file.filename||""),parts=this.fileNameParts(name),url=this.signedFiles.get(file.id),content=`<span style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(parts.base)}</span><span style="flex:none;white-space:nowrap">${esc(parts.extension)}</span>`,style="display:inline-flex;align-items:center;max-width:160px;min-width:0;color:var(--primary-color);text-decoration:none";return url?`<button type="button" class="pill file-pill file-open" data-file-open="${esc(file.id)}" title="${esc(name)}" style="${style};min-height:0;padding:3px 8px;border:0">${content}</button>`:`<span class="pill file-pill" title="${esc(name)}" style="${style}">${content}</span>`;}
  taskRow(t){ const files=this.attachments.filter(a=>a.task_id===t.id),assignee=this.users.find(user=>user.id===t.assignee_user_id),tagName=this.tagName(t),filePills=files.map(file=>this.filePill(file)).join("");return `<div class="task" data-task="${t.id}" tabindex="0" style="display:grid;grid-template-columns:minmax(0,1fr) 44px;align-items:center;gap:4px;padding:5px 6px 7px 10px"><div class="task-body" style="display:block;min-width:0"><div style="display:flex;align-items:center;gap:6px;flex-wrap:wrap"><strong class="ht-content">${esc(t.name)}</strong>${tagName?`<span class="pill ht-content-small"><ha-icon icon="mdi:nfc"></ha-icon>${esc(tagName)}</span>`:""}</div><div class="pills" style="display:flex;gap:6px;flex-wrap:wrap;align-items:center"><span class="pill due-date ${this.due(t)?"due":"ok"}" title="${esc(this.date(t.due_date))}">${esc(this.relativeDate(t.due_date))}</span>${assignee?`<span class="pill">${esc(assignee.name)}</span>`:""}</div>${filePills?`<div class="pills" style="display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin-top:6px">${filePills}</div>`:""}</div>${rowActionButtonHtml("task",t.id)}</div>`; }
  wireGroup(el){ const g=this.groups.find(x=>x.id===el.dataset.group),head=el.querySelector(".group-head"),toggle=()=>{this.expanded.has(g.id)?this.expanded.delete(g.id):this.expanded.add(g.id);this.render();};head.onclick=toggle;head.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")toggle();};const groupActions=el.querySelector('.row-action-toggle[data-action-kind="group"]');groupActions.onclick=e=>{e.stopPropagation();this.actionMenu(groupActions,()=>this.groupEditor(g),()=>this.deleteGroup(g));};const groupAdd=el.querySelector(".group-add");if(groupAdd)groupAdd.onclick=()=>this.taskEditor(g.id);el.querySelectorAll("[data-task]").forEach(row=>{const t=this.tasks.find(x=>x.id===row.dataset.task),taskActions=row.querySelector('.row-action-toggle[data-action-kind="task"]');row.onclick=()=>this.taskViewer(t);row.onkeydown=e=>{if(e.target===row&&(e.key==="Enter"||e.key===" "))this.taskViewer(t);};taskActions.onclick=e=>{e.stopPropagation();this.actionMenu(taskActions,()=>this.taskEditor(g.id,t),()=>this.deleteTask(t));};});this.wireFileOpeners(el); }
};
