// Read-only task viewer (description via HA's native ha-markdown, files,
// history, complete action). Assigned to the panel prototype in panel.js.
import { esc, L } from "./utils.js";

export async function taskViewer(task){
  const root=this.shadowRoot.querySelector(".dialogs"),group=this.groups.find(item=>item.id===task.group_id),assignee=this.users.find(user=>user.id===task.assignee_user_id),files=this.attachments.filter(file=>file.task_id===task.id);
  root.innerHTML=`<div class="overlay viewer-overlay"><div class="modal task-viewer" role="dialog" aria-modal="true" aria-labelledby="task-viewer-title">${this.modalHeader(esc(task.name),"task-viewer-title")}<div class="viewer-pills"><span class="pill"><ha-icon icon="mdi:devices"></ha-icon>${esc(group?.name||"Keine Gruppe")}</span><span class="pill"><ha-icon icon="mdi:account"></ha-icon>${esc(assignee?.name||"Nicht zugewiesen")}</span></div><section class="viewer-section"><h3>Beschreibung</h3><div class="viewer-description"></div></section><section class="viewer-section"><h3>Planung</h3><p>${esc(this.scheduleText(task))}</p></section><section class="details viewer-box"><h3>${L.files}</h3><div class="viewer-file-list">${files.length?files.map(file=>`<div class="detail-row">${this.fileLink(file)}<span class="file-size">${this.size(file.size)}</span></div>`).join(""):`<small>${L.noFiles}</small>`}</div></section><section class="details viewer-box"><h3>${L.history}</h3><div class="viewer-history-list">Laden…</div></section><label class="viewer-notes"><span>Notizen zur Erledigung</span><textarea placeholder="Optionale Notizen für den Verlauf"></textarea></label><div class="viewer-actions"><button type="button" class="viewer-complete"><ha-icon icon="mdi:check-circle-outline"></ha-icon><span>Erledigt</span></button></div></div></div>`;
  const description=root.querySelector(".viewer-description");if(task.description){const md=document.createElement("ha-markdown");md.breaks=true;md.content=task.description;description.appendChild(md);}else description.innerHTML="<p>Keine Beschreibung</p>";
  let closed=false;const close=()=>{if(closed)return;closed=true;window.removeEventListener("keydown",onKey);root.innerHTML="";},onKey=e=>{if(e.key==="Escape")close();};window.addEventListener("keydown",onKey);root.querySelector(".modal-close").onclick=close;root.querySelector(".viewer-overlay").onclick=e=>{if(e.target===e.currentTarget)close();};root.querySelector(".viewer-complete").onclick=async()=>{const notes=root.querySelector(".viewer-notes textarea").value.trim()||null;if(!await this.confirmAction("Task erledigen",`Möchtest du den Task „${task.name}“ als erledigt markieren?`,"Erledigen","success","mdi:check-circle-outline"))return;await this.ws({type:"home_tasker/task/complete",task_id:task.id,notes});close();await this.load();};
  try{const data=await this.ws({type:"home_tasker/history/list",task_id:task.id});if(closed)return;const history=root.querySelector(".viewer-history-list");history.innerHTML=data.history.length?data.history.map(entry=>this.historyRow(entry)).join(""):`<small>${L.noHistory}</small>`;}catch(err){if(!closed)root.querySelector(".viewer-history-list").innerHTML=`<small>Verlauf konnte nicht geladen werden: ${esc(err.message||err)}</small>`;}
}
export function historyRow(entry,deletable=false){return `<div class="detail-row history-entry" data-history="${entry.id}" style="display:grid;grid-template-columns:max-content max-content max-content minmax(0,1fr)${deletable?" 44px":""};gap:8px;align-items:start"><span title="Datum">${this.date(entry.completion_date)}</span><span title="Zeit">${this.historyTime(entry)}</span><span title="Benutzer">${esc(entry.user_name||"system")}</span><span title="Notizen" style="min-width:0;white-space:pre-wrap;overflow-wrap:anywhere">${entry.notes?esc(entry.notes):"–"}</span>${deletable?'<button type="button" class="editor-action remove danger" aria-label="Verlaufseintrag entfernen" title="Entfernen" style="justify-self:end"><ha-icon icon="mdi:delete"></ha-icon></button>':""}</div>`;}
export function fileLink(file){const name=esc(file.filename),url=this.signedFiles.get(file.id);return url?`<a class="filename" href="${esc(url)}" target="_blank" rel="noopener noreferrer" title="${name}" style="min-width:0;white-space:nowrap;text-overflow:ellipsis;display:block">${name}</a>`:`<span class="filename" title="${name}" style="min-width:0;white-space:nowrap;text-overflow:ellipsis;display:block">${name}</span>`;}
